// This file is auto-generated by @hey-api/openapi-ts

import * as z from "zod";

/**
 * _Binding_rank_OrderByInput
 */
export const PlaylistsModelsBindingRankOrderByInputSchema = z.object({
  rank: z.enum(["asc", "desc"]),
});

/**
 * _Binding_playlistId_OrderByInput
 */
export const PlaylistsModelsBindingPlaylistIdOrderByInputSchema = z.object({
  playlistId: z.enum(["asc", "desc"]),
});

/**
 * _Binding_mediaId_OrderByInput
 */
export const PlaylistsModelsBindingMediaIdOrderByInputSchema = z.object({
  mediaId: z.enum(["asc", "desc"]),
});

/**
 * _Binding_id_OrderByInput
 */
export const PlaylistsModelsBindingIdOrderByInputSchema = z.object({
  id: z.enum(["asc", "desc"]),
});

/**
 * _Binding_RelevanceInner
 */
export const PlaylistsModelsBindingRelevanceInnerSchema = z.object({
  fields: z.array(z.enum(["id", "playlistId", "mediaId", "rank"])),
  search: z.string(),
  sort: z.enum(["asc", "desc"]),
});

/**
 * _Binding_RelevanceOrderByInput
 */
export const PlaylistsModelsBindingRelevanceOrderByInputSchema = z.object({
  _relevance: PlaylistsModelsBindingRelevanceInnerSchema,
});

/**
 * _BindingWhereUnique_id_Input
 */
export const PlaylistsModelsBindingWhereUniqueIdInputSchema = z.object({
  id: z.string(),
});

/**
 * _BindingCompoundplaylistId_rankKeyInner
 */
export const PlaylistsModelsBindingCompoundplaylistIdRankKeyInnerSchema =
  z.object({
    playlistId: z.string(),
    rank: z.string(),
  });

/**
 * _BindingCompoundplaylistId_rankKey
 */
export const PlaylistsModelsBindingCompoundplaylistIdRankKeySchema = z.object({
  playlistidRank: PlaylistsModelsBindingCompoundplaylistIdRankKeyInnerSchema,
});

/**
 * StringFilter
 */
export const PlaylistsModelsStringFilterSchema = z.object({
  equals: z.string().optional(),
  notIn: z.array(z.string()).optional(),
  lt: z.string().optional(),
  lte: z.string().optional(),
  gt: z.string().optional(),
  gte: z.string().optional(),
  contains: z.string().optional(),
  startswith: z.string().optional(),
  endswith: z.string().optional(),
  in: z.array(z.string()).optional(),
  get not() {
    return z.union([z.string(), PlaylistsModelsStringFilterSchema]).optional();
  },
  mode: z.enum(["default", "insensitive"]).optional(),
  search: z.string().optional(),
});

export const PlaylistsModelsUpdateRequestIdSchema = z.uuid();

/**
 * PlaylistUpdateManyMutationInput
 *
 * Arguments for updating many records
 */
export const PlaylistsModelsUpdateRequestDataSchema = z
  .object({
    id: z.string().optional(),
    name: z.string().optional(),
  })
  .register(z.globalRegistry, {
    description: "Arguments for updating many records",
  });

/**
 * _Playlist_name_OrderByInput
 */
export const PlaylistNameOrderByInputSchema = z.object({
  name: z.enum(["asc", "desc"]),
});

/**
 * _Playlist_id_OrderByInput
 */
export const PlaylistIdOrderByInputSchema = z.object({
  id: z.enum(["asc", "desc"]),
});

export const PlaylistOrderByInputSchema = z.union([
  PlaylistIdOrderByInputSchema,
  PlaylistNameOrderByInputSchema,
]);

export const PlaylistsModelsListRequestOrderSchema = z
  .union([PlaylistOrderByInputSchema, z.array(PlaylistOrderByInputSchema)])
  .nullable();

export const PlaylistsModelsListRequestOffsetSchema = z.int().nullable();

export const PlaylistsModelsListRequestLimitSchema = z.int().nullable();

export const PlaylistsModelsGetRequestIdSchema = z.uuid();

export const PlaylistsModelsDeleteRequestIdSchema = z.uuid();

/**
 * PlaylistCreateWithoutRelationsInput
 *
 * Required arguments to the Playlist create method, without relations
 */
export const PlaylistsModelsCreateRequestDataSchema = z
  .object({
    id: z.string().optional(),
    name: z.string(),
  })
  .register(z.globalRegistry, {
    description:
      "Required arguments to the Playlist create method, without relations",
  });

/**
 * _Binding_rank_OrderByInput
 */
export const MediaModelsBindingRankOrderByInputSchema = z.object({
  rank: z.enum(["asc", "desc"]),
});

/**
 * _Binding_playlistId_OrderByInput
 */
export const MediaModelsBindingPlaylistIdOrderByInputSchema = z.object({
  playlistId: z.enum(["asc", "desc"]),
});

/**
 * _Binding_mediaId_OrderByInput
 */
export const MediaModelsBindingMediaIdOrderByInputSchema = z.object({
  mediaId: z.enum(["asc", "desc"]),
});

/**
 * _Binding_id_OrderByInput
 */
export const MediaModelsBindingIdOrderByInputSchema = z.object({
  id: z.enum(["asc", "desc"]),
});

/**
 * _Binding_RelevanceInner
 */
export const MediaModelsBindingRelevanceInnerSchema = z.object({
  fields: z.array(z.enum(["id", "playlistId", "mediaId", "rank"])),
  search: z.string(),
  sort: z.enum(["asc", "desc"]),
});

/**
 * _Binding_RelevanceOrderByInput
 */
export const MediaModelsBindingRelevanceOrderByInputSchema = z.object({
  _relevance: MediaModelsBindingRelevanceInnerSchema,
});

/**
 * _BindingWhereUnique_id_Input
 */
export const MediaModelsBindingWhereUniqueIdInputSchema = z.object({
  id: z.string(),
});

/**
 * _BindingCompoundplaylistId_rankKeyInner
 */
export const MediaModelsBindingCompoundplaylistIdRankKeyInnerSchema = z.object({
  playlistId: z.string(),
  rank: z.string(),
});

/**
 * _BindingCompoundplaylistId_rankKey
 */
export const MediaModelsBindingCompoundplaylistIdRankKeySchema = z.object({
  playlistidRank: MediaModelsBindingCompoundplaylistIdRankKeyInnerSchema,
});

/**
 * StringFilter
 */
export const MediaModelsStringFilterSchema = z.object({
  equals: z.string().optional(),
  notIn: z.array(z.string()).optional(),
  lt: z.string().optional(),
  lte: z.string().optional(),
  gt: z.string().optional(),
  gte: z.string().optional(),
  contains: z.string().optional(),
  startswith: z.string().optional(),
  endswith: z.string().optional(),
  in: z.array(z.string()).optional(),
  get not() {
    return z.union([z.string(), MediaModelsStringFilterSchema]).optional();
  },
  mode: z.enum(["default", "insensitive"]).optional(),
  search: z.string().optional(),
});

export const MediaModelsUpdateRequestIdSchema = z.uuid();

/**
 * MediaUpdateManyMutationInput
 *
 * Arguments for updating many records
 */
export const MediaModelsUpdateRequestDataSchema = z
  .object({
    id: z.string().optional(),
    name: z.string().optional(),
  })
  .register(z.globalRegistry, {
    description: "Arguments for updating many records",
  });

/**
 * _Media_name_OrderByInput
 */
export const MediaNameOrderByInputSchema = z.object({
  name: z.enum(["asc", "desc"]),
});

/**
 * _Media_id_OrderByInput
 */
export const MediaIdOrderByInputSchema = z.object({
  id: z.enum(["asc", "desc"]),
});

export const MediaOrderByInputSchema = z.union([
  MediaIdOrderByInputSchema,
  MediaNameOrderByInputSchema,
]);

export const MediaModelsListRequestOrderSchema = z
  .union([MediaOrderByInputSchema, z.array(MediaOrderByInputSchema)])
  .nullable();

export const MediaModelsListRequestOffsetSchema = z.int().nullable();

export const MediaModelsListRequestLimitSchema = z.int().nullable();

export const MediaModelsGetRequestIdSchema = z.uuid();

export const MediaModelsDeleteRequestIdSchema = z.uuid();

/**
 * MediaCreateWithoutRelationsInput
 *
 * Required arguments to the Media create method, without relations
 */
export const MediaModelsCreateRequestDataSchema = z
  .object({
    id: z.string().optional(),
    name: z.string(),
  })
  .register(z.globalRegistry, {
    description:
      "Required arguments to the Media create method, without relations",
  });

/**
 * _Binding_rank_OrderByInput
 */
export const BindingsModelsBindingRankOrderByInputSchema = z.object({
  rank: z.enum(["asc", "desc"]),
});

/**
 * _Binding_playlistId_OrderByInput
 */
export const BindingsModelsBindingPlaylistIdOrderByInputSchema = z.object({
  playlistId: z.enum(["asc", "desc"]),
});

/**
 * _Binding_mediaId_OrderByInput
 */
export const BindingsModelsBindingMediaIdOrderByInputSchema = z.object({
  mediaId: z.enum(["asc", "desc"]),
});

/**
 * _Binding_id_OrderByInput
 */
export const BindingsModelsBindingIdOrderByInputSchema = z.object({
  id: z.enum(["asc", "desc"]),
});

/**
 * _Binding_RelevanceInner
 */
export const BindingsModelsBindingRelevanceInnerSchema = z.object({
  fields: z.array(z.enum(["id", "playlistId", "mediaId", "rank"])),
  search: z.string(),
  sort: z.enum(["asc", "desc"]),
});

/**
 * _Binding_RelevanceOrderByInput
 */
export const BindingsModelsBindingRelevanceOrderByInputSchema = z.object({
  _relevance: BindingsModelsBindingRelevanceInnerSchema,
});

/**
 * _BindingWhereUnique_id_Input
 */
export const BindingsModelsBindingWhereUniqueIdInputSchema = z.object({
  id: z.string(),
});

/**
 * _BindingCompoundplaylistId_rankKeyInner
 */
export const BindingsModelsBindingCompoundplaylistIdRankKeyInnerSchema =
  z.object({
    playlistId: z.string(),
    rank: z.string(),
  });

/**
 * _BindingCompoundplaylistId_rankKey
 */
export const BindingsModelsBindingCompoundplaylistIdRankKeySchema = z.object({
  playlistidRank: BindingsModelsBindingCompoundplaylistIdRankKeyInnerSchema,
});

/**
 * StringFilter
 */
export const BindingsModelsStringFilterSchema = z.object({
  equals: z.string().optional(),
  notIn: z.array(z.string()).optional(),
  lt: z.string().optional(),
  lte: z.string().optional(),
  gt: z.string().optional(),
  gte: z.string().optional(),
  contains: z.string().optional(),
  startswith: z.string().optional(),
  endswith: z.string().optional(),
  in: z.array(z.string()).optional(),
  get not() {
    return z.union([z.string(), BindingsModelsStringFilterSchema]).optional();
  },
  mode: z.enum(["default", "insensitive"]).optional(),
  search: z.string().optional(),
});

export const BindingsModelsUpdateRequestIdSchema = z.uuid();

/**
 * BindingUpdateManyMutationInput
 *
 * Arguments for updating many records
 */
export const BindingsModelsUpdateRequestDataSchema = z
  .object({
    id: z.string().optional(),
    rank: z.string().optional(),
  })
  .register(z.globalRegistry, {
    description: "Arguments for updating many records",
  });

export const BindingOrderByInputSchema = z.union([
  BindingsModelsBindingIdOrderByInputSchema,
  BindingsModelsBindingPlaylistIdOrderByInputSchema,
  BindingsModelsBindingMediaIdOrderByInputSchema,
  BindingsModelsBindingRankOrderByInputSchema,
]);

export const BindingsModelsListRequestOrderSchema = z
  .union([BindingOrderByInputSchema, z.array(BindingOrderByInputSchema)])
  .nullable();

export const BindingsModelsListRequestOffsetSchema = z.int().nullable();

export const BindingsModelsListRequestLimitSchema = z.int().nullable();

export const BindingsModelsGetRequestIdSchema = z.uuid();

export const BindingsModelsDeleteRequestIdSchema = z.uuid();

/**
 * BindingCreateInput
 *
 * Required arguments to the Binding create method.
 */
export const BindingsModelsCreateRequestDataSchema = z
  .object({
    id: z.string().optional(),
    playlistId: z.string().register(z.globalRegistry, {
      description: "Identifier of the playlist.",
    }),
    mediaId: z.string().register(z.globalRegistry, {
      description: "Identifier of the media.",
    }),
    rank: z.string().register(z.globalRegistry, {
      description: "Rank of the binding.",
    }),
  })
  .register(z.globalRegistry, {
    description: "Required arguments to the Binding create method.",
  });

export const UploadRequestTypeSchema = z.string();

export const UploadRequestIdSchema = z.uuid();

/**
 * Result
 *
 * Result of the test.
 */
export const TestResponseResultSchema = z
  .object({
    success: z.boolean().register(z.globalRegistry, {
      description: "Indicates if the test was successful.",
    }),
    message: z.string().register(z.globalRegistry, {
      description: "Message returned from the test.",
    }),
  })
  .register(z.globalRegistry, {
    description: "Result of the test.",
  });

/**
 * Parameters
 *
 * Parameters for testing.
 */
export const ParametersSchema = z
  .object({
    message: z.string().nullish().default(null),
  })
  .register(z.globalRegistry, {
    description: "Parameters for testing.",
  });

export const TestRequestParametersSchema = ParametersSchema.nullable();

/**
 * EventType
 *
 * Event types.
 */
export const EventTypeSchema = z
  .enum([
    "test",
    "binding-created",
    "binding-updated",
    "binding-deleted",
    "media-created",
    "media-updated",
    "media-deleted",
    "playlist-created",
    "playlist-updated",
    "playlist-deleted",
  ])
  .register(z.globalRegistry, {
    description: "Event types.",
  });

export const SubscribeRequestTypesSchema = z
  .union([z.string(), z.array(EventTypeSchema)])
  .nullable();

export const M3uRequestIdSchema = z.uuid();

export const HeadM3uRequestIdSchema = z.uuid();

export const DownloadRequestIdSchema = z.uuid();

export const PlaylistsModelsUpdateRequestIncludeSchema = z
  .lazy(() => PlaylistIncludeSchema)
  .nullable();

/**
 * FindManyBindingArgsFromMedia
 *
 * Arguments for Media
 */
export const PlaylistsModelsFindManyBindingArgsFromMediaSchema = z
  .object({
    take: z.int().optional(),
    skip: z.int().optional(),
    orderBy: z
      .union([
        PlaylistsModelsBindingIdOrderByInputSchema,
        PlaylistsModelsBindingPlaylistIdOrderByInputSchema,
        PlaylistsModelsBindingMediaIdOrderByInputSchema,
        PlaylistsModelsBindingRankOrderByInputSchema,
        PlaylistsModelsBindingRelevanceOrderByInputSchema,
        z.array(
          z.union([
            PlaylistsModelsBindingIdOrderByInputSchema,
            PlaylistsModelsBindingPlaylistIdOrderByInputSchema,
            PlaylistsModelsBindingMediaIdOrderByInputSchema,
            PlaylistsModelsBindingRankOrderByInputSchema,
            PlaylistsModelsBindingRelevanceOrderByInputSchema,
          ]),
        ),
      ])
      .optional(),
    get where() {
      return PlaylistsModelsBindingWhereInputSchema.optional();
    },
    cursor: z
      .union([
        PlaylistsModelsBindingWhereUniqueIdInputSchema,
        PlaylistsModelsBindingCompoundplaylistIdRankKeySchema,
      ])
      .optional(),
    distinct: z
      .array(z.enum(["id", "playlistId", "mediaId", "rank"]))
      .optional(),
    get include() {
      return PlaylistsModelsBindingIncludeFromBindingSchema.optional();
    },
  })
  .register(z.globalRegistry, {
    description: "Arguments for Media",
  });

/**
 * BindingIncludeFromBinding
 *
 * Relational arguments for Binding
 */
export const PlaylistsModelsBindingIncludeFromBindingSchema = z
  .object({
    playlist: z
      .union([
        z.boolean(),
        z.lazy((): any => PlaylistsModelsPlaylistArgsFromBindingSchema),
      ])
      .optional(),
    media: z
      .union([
        z.boolean(),
        z.lazy((): any => PlaylistsModelsMediaArgsFromBindingSchema),
      ])
      .optional(),
  })
  .register(z.globalRegistry, {
    description: "Relational arguments for Binding",
  });

/**
 * BindingListRelationFilter
 */
export const PlaylistsModelsBindingListRelationFilterSchema = z.object({
  get some() {
    return PlaylistsModelsBindingWhereInputSchema.optional();
  },
  get none() {
    return PlaylistsModelsBindingWhereInputSchema.optional();
  },
  get every() {
    return PlaylistsModelsBindingWhereInputSchema.optional();
  },
});

/**
 * MediaWhereInput
 *
 * Media arguments for searching
 */
export const PlaylistsModelsMediaWhereInputSchema = z
  .object({
    id: z.union([z.string(), PlaylistsModelsStringFilterSchema]).optional(),
    name: z.union([z.string(), PlaylistsModelsStringFilterSchema]).optional(),
    bindings: PlaylistsModelsBindingListRelationFilterSchema.optional(),
    and: z
      .array(z.lazy((): any => PlaylistsModelsMediaWhereInputSchema))
      .optional(),
    or: z
      .array(z.lazy((): any => PlaylistsModelsMediaWhereInputSchema))
      .optional(),
    not: z
      .array(z.lazy((): any => PlaylistsModelsMediaWhereInputSchema))
      .optional(),
  })
  .register(z.globalRegistry, {
    description: "Media arguments for searching",
  });

/**
 * MediaRelationFilter
 */
export const PlaylistsModelsMediaRelationFilterSchema = z.object({
  is: PlaylistsModelsMediaWhereInputSchema.optional(),
  isNot: PlaylistsModelsMediaWhereInputSchema.optional(),
});

/**
 * PlaylistWhereInput
 *
 * Playlist arguments for searching
 */
export const PlaylistsModelsPlaylistWhereInputSchema = z
  .object({
    id: z.union([z.string(), PlaylistsModelsStringFilterSchema]).optional(),
    name: z.union([z.string(), PlaylistsModelsStringFilterSchema]).optional(),
    bindings: PlaylistsModelsBindingListRelationFilterSchema.optional(),
    and: z
      .array(z.lazy((): any => PlaylistsModelsPlaylistWhereInputSchema))
      .optional(),
    or: z
      .array(z.lazy((): any => PlaylistsModelsPlaylistWhereInputSchema))
      .optional(),
    not: z
      .array(z.lazy((): any => PlaylistsModelsPlaylistWhereInputSchema))
      .optional(),
  })
  .register(z.globalRegistry, {
    description: "Playlist arguments for searching",
  });

/**
 * PlaylistRelationFilter
 */
export const PlaylistsModelsPlaylistRelationFilterSchema = z.object({
  is: PlaylistsModelsPlaylistWhereInputSchema.optional(),
  isNot: PlaylistsModelsPlaylistWhereInputSchema.optional(),
});

/**
 * BindingWhereInput
 *
 * Binding arguments for searching
 */
export const PlaylistsModelsBindingWhereInputSchema = z
  .object({
    id: z.union([z.string(), PlaylistsModelsStringFilterSchema]).optional(),
    playlistId: z
      .union([z.string(), PlaylistsModelsStringFilterSchema])
      .optional(),
    mediaId: z
      .union([z.string(), PlaylistsModelsStringFilterSchema])
      .optional(),
    rank: z.union([z.string(), PlaylistsModelsStringFilterSchema]).optional(),
    playlist: PlaylistsModelsPlaylistRelationFilterSchema.optional(),
    media: PlaylistsModelsMediaRelationFilterSchema.optional(),
    and: z
      .array(z.lazy((): any => PlaylistsModelsBindingWhereInputSchema))
      .optional(),
    or: z
      .array(z.lazy((): any => PlaylistsModelsBindingWhereInputSchema))
      .optional(),
    not: z
      .array(z.lazy((): any => PlaylistsModelsBindingWhereInputSchema))
      .optional(),
  })
  .register(z.globalRegistry, {
    description: "Binding arguments for searching",
  });

/**
 * MediaIncludeFromMedia
 *
 * Relational arguments for Media
 */
export const PlaylistsModelsMediaIncludeFromMediaSchema = z
  .object({
    bindings: z
      .union([z.boolean(), PlaylistsModelsFindManyBindingArgsFromMediaSchema])
      .optional(),
  })
  .register(z.globalRegistry, {
    description: "Relational arguments for Media",
  });

/**
 * MediaArgsFromBinding
 *
 * Arguments for Binding
 */
export const PlaylistsModelsMediaArgsFromBindingSchema = z
  .object({
    include: PlaylistsModelsMediaIncludeFromMediaSchema.optional(),
  })
  .register(z.globalRegistry, {
    description: "Arguments for Binding",
  });

/**
 * FindManyBindingArgsFromPlaylist
 *
 * Arguments for Playlist
 */
export const PlaylistsModelsFindManyBindingArgsFromPlaylistSchema = z
  .object({
    take: z.int().optional(),
    skip: z.int().optional(),
    orderBy: z
      .union([
        PlaylistsModelsBindingIdOrderByInputSchema,
        PlaylistsModelsBindingPlaylistIdOrderByInputSchema,
        PlaylistsModelsBindingMediaIdOrderByInputSchema,
        PlaylistsModelsBindingRankOrderByInputSchema,
        PlaylistsModelsBindingRelevanceOrderByInputSchema,
        z.array(
          z.union([
            PlaylistsModelsBindingIdOrderByInputSchema,
            PlaylistsModelsBindingPlaylistIdOrderByInputSchema,
            PlaylistsModelsBindingMediaIdOrderByInputSchema,
            PlaylistsModelsBindingRankOrderByInputSchema,
            PlaylistsModelsBindingRelevanceOrderByInputSchema,
          ]),
        ),
      ])
      .optional(),
    where: PlaylistsModelsBindingWhereInputSchema.optional(),
    cursor: z
      .union([
        PlaylistsModelsBindingWhereUniqueIdInputSchema,
        PlaylistsModelsBindingCompoundplaylistIdRankKeySchema,
      ])
      .optional(),
    distinct: z
      .array(z.enum(["id", "playlistId", "mediaId", "rank"]))
      .optional(),
    include: PlaylistsModelsBindingIncludeFromBindingSchema.optional(),
  })
  .register(z.globalRegistry, {
    description: "Arguments for Playlist",
  });

/**
 * PlaylistIncludeFromPlaylist
 *
 * Relational arguments for Playlist
 */
export const PlaylistsModelsPlaylistIncludeFromPlaylistSchema = z
  .object({
    bindings: z
      .union([
        z.boolean(),
        PlaylistsModelsFindManyBindingArgsFromPlaylistSchema,
      ])
      .optional(),
  })
  .register(z.globalRegistry, {
    description: "Relational arguments for Playlist",
  });

/**
 * PlaylistArgsFromBinding
 *
 * Arguments for Binding
 */
export const PlaylistsModelsPlaylistArgsFromBindingSchema = z
  .object({
    include: PlaylistsModelsPlaylistIncludeFromPlaylistSchema.optional(),
  })
  .register(z.globalRegistry, {
    description: "Arguments for Binding",
  });

/**
 * PlaylistInclude
 *
 * Playlist relational arguments
 */
export const PlaylistIncludeSchema = z
  .object({
    bindings: z
      .union([
        z.boolean(),
        PlaylistsModelsFindManyBindingArgsFromPlaylistSchema,
      ])
      .optional(),
  })
  .register(z.globalRegistry, {
    description: "Playlist relational arguments",
  });

/**
 * Playlist
 *
 * Playlist data.
 */
export const PlaylistsModelsPlaylistSchema = z
  .object({
    id: z.uuid().register(z.globalRegistry, {
      description: "Identifier of the playlist.",
    }),
    name: z.string().register(z.globalRegistry, {
      description: "Name of the playlist.",
    }),
    bindings: z
      .array(z.lazy((): any => PlaylistsModelsBindingSchema))
      .nullable(),
  })
  .register(z.globalRegistry, {
    description: "Playlist data.",
  });

/**
 * Media
 *
 * Media data.
 */
export const PlaylistsModelsMediaSchema = z
  .object({
    id: z.uuid().register(z.globalRegistry, {
      description: "Identifier of the media.",
    }),
    name: z.string().register(z.globalRegistry, {
      description: "Name of the media.",
    }),
    bindings: z
      .array(z.lazy((): any => PlaylistsModelsBindingSchema))
      .nullable(),
  })
  .register(z.globalRegistry, {
    description: "Media data.",
  });

/**
 * Binding
 *
 * Binding data.
 */
export const PlaylistsModelsBindingSchema = z
  .object({
    id: z.uuid().register(z.globalRegistry, {
      description: "Identifier of the binding.",
    }),
    playlistId: z.uuid().register(z.globalRegistry, {
      description: "Identifier of the playlist that the binding belongs to.",
    }),
    mediaId: z.uuid().register(z.globalRegistry, {
      description: "Identifier of the media that the binding belongs to.",
    }),
    rank: z.string().register(z.globalRegistry, {
      description: "Rank of the media in the binding.",
    }),
    playlist: PlaylistsModelsPlaylistSchema.nullable(),
    media: PlaylistsModelsMediaSchema.nullable(),
  })
  .register(z.globalRegistry, {
    description: "Binding data.",
  });

/**
 * PlaylistList
 *
 * List of playlists.
 */
export const PlaylistsModelsListResponseResultsSchema = z
  .object({
    count: z.int().register(z.globalRegistry, {
      description: "Total number of playlists that matched the query.",
    }),
    limit: z.int().nullable(),
    offset: z.int().nullable(),
    playlists: z
      .array(PlaylistsModelsPlaylistSchema)
      .register(z.globalRegistry, {
        description: "Playlists that matched the request.",
      }),
  })
  .register(z.globalRegistry, {
    description: "List of playlists.",
  });

export const PlaylistsModelsListRequestWhereSchema =
  PlaylistsModelsPlaylistWhereInputSchema.nullable();

export const PlaylistsModelsListRequestIncludeSchema =
  PlaylistIncludeSchema.nullable();

export const PlaylistsModelsGetRequestIncludeSchema =
  PlaylistIncludeSchema.nullable();

export const PlaylistsModelsCreateRequestIncludeSchema =
  PlaylistIncludeSchema.nullable();

export const MediaModelsUpdateRequestIncludeSchema = z
  .lazy(() => MediaIncludeSchema)
  .nullable();

/**
 * MediaIncludeFromMedia
 *
 * Relational arguments for Media
 */
export const MediaModelsMediaIncludeFromMediaSchema = z
  .object({
    bindings: z
      .union([
        z.boolean(),
        z.lazy((): any => MediaModelsFindManyBindingArgsFromMediaSchema),
      ])
      .optional(),
  })
  .register(z.globalRegistry, {
    description: "Relational arguments for Media",
  });

/**
 * FindManyBindingArgsFromMedia
 *
 * Arguments for Media
 */
export const MediaModelsFindManyBindingArgsFromMediaSchema = z
  .object({
    take: z.int().optional(),
    skip: z.int().optional(),
    orderBy: z
      .union([
        MediaModelsBindingIdOrderByInputSchema,
        MediaModelsBindingPlaylistIdOrderByInputSchema,
        MediaModelsBindingMediaIdOrderByInputSchema,
        MediaModelsBindingRankOrderByInputSchema,
        MediaModelsBindingRelevanceOrderByInputSchema,
        z.array(
          z.union([
            MediaModelsBindingIdOrderByInputSchema,
            MediaModelsBindingPlaylistIdOrderByInputSchema,
            MediaModelsBindingMediaIdOrderByInputSchema,
            MediaModelsBindingRankOrderByInputSchema,
            MediaModelsBindingRelevanceOrderByInputSchema,
          ]),
        ),
      ])
      .optional(),
    get where() {
      return MediaModelsBindingWhereInputSchema.optional();
    },
    cursor: z
      .union([
        MediaModelsBindingWhereUniqueIdInputSchema,
        MediaModelsBindingCompoundplaylistIdRankKeySchema,
      ])
      .optional(),
    distinct: z
      .array(z.enum(["id", "playlistId", "mediaId", "rank"]))
      .optional(),
    get include() {
      return MediaModelsBindingIncludeFromBindingSchema.optional();
    },
  })
  .register(z.globalRegistry, {
    description: "Arguments for Media",
  });

/**
 * MediaArgsFromBinding
 *
 * Arguments for Binding
 */
export const MediaModelsMediaArgsFromBindingSchema = z
  .object({
    include: MediaModelsMediaIncludeFromMediaSchema.optional(),
  })
  .register(z.globalRegistry, {
    description: "Arguments for Binding",
  });

/**
 * FindManyBindingArgsFromPlaylist
 *
 * Arguments for Playlist
 */
export const MediaModelsFindManyBindingArgsFromPlaylistSchema = z
  .object({
    take: z.int().optional(),
    skip: z.int().optional(),
    orderBy: z
      .union([
        MediaModelsBindingIdOrderByInputSchema,
        MediaModelsBindingPlaylistIdOrderByInputSchema,
        MediaModelsBindingMediaIdOrderByInputSchema,
        MediaModelsBindingRankOrderByInputSchema,
        MediaModelsBindingRelevanceOrderByInputSchema,
        z.array(
          z.union([
            MediaModelsBindingIdOrderByInputSchema,
            MediaModelsBindingPlaylistIdOrderByInputSchema,
            MediaModelsBindingMediaIdOrderByInputSchema,
            MediaModelsBindingRankOrderByInputSchema,
            MediaModelsBindingRelevanceOrderByInputSchema,
          ]),
        ),
      ])
      .optional(),
    get where() {
      return MediaModelsBindingWhereInputSchema.optional();
    },
    cursor: z
      .union([
        MediaModelsBindingWhereUniqueIdInputSchema,
        MediaModelsBindingCompoundplaylistIdRankKeySchema,
      ])
      .optional(),
    distinct: z
      .array(z.enum(["id", "playlistId", "mediaId", "rank"]))
      .optional(),
    get include() {
      return MediaModelsBindingIncludeFromBindingSchema.optional();
    },
  })
  .register(z.globalRegistry, {
    description: "Arguments for Playlist",
  });

/**
 * BindingIncludeFromBinding
 *
 * Relational arguments for Binding
 */
export const MediaModelsBindingIncludeFromBindingSchema = z
  .object({
    playlist: z
      .union([
        z.boolean(),
        z.lazy((): any => MediaModelsPlaylistArgsFromBindingSchema),
      ])
      .optional(),
    media: z
      .union([z.boolean(), MediaModelsMediaArgsFromBindingSchema])
      .optional(),
  })
  .register(z.globalRegistry, {
    description: "Relational arguments for Binding",
  });

/**
 * MediaWhereInput
 *
 * Media arguments for searching
 */
export const MediaModelsMediaWhereInputSchema = z
  .object({
    id: z.union([z.string(), MediaModelsStringFilterSchema]).optional(),
    name: z.union([z.string(), MediaModelsStringFilterSchema]).optional(),
    get bindings() {
      return MediaModelsBindingListRelationFilterSchema.optional();
    },
    and: z
      .array(z.lazy((): any => MediaModelsMediaWhereInputSchema))
      .optional(),
    or: z.array(z.lazy((): any => MediaModelsMediaWhereInputSchema)).optional(),
    not: z
      .array(z.lazy((): any => MediaModelsMediaWhereInputSchema))
      .optional(),
  })
  .register(z.globalRegistry, {
    description: "Media arguments for searching",
  });

/**
 * MediaRelationFilter
 */
export const MediaModelsMediaRelationFilterSchema = z.object({
  is: MediaModelsMediaWhereInputSchema.optional(),
  isNot: MediaModelsMediaWhereInputSchema.optional(),
});

/**
 * PlaylistWhereInput
 *
 * Playlist arguments for searching
 */
export const MediaModelsPlaylistWhereInputSchema = z
  .object({
    id: z.union([z.string(), MediaModelsStringFilterSchema]).optional(),
    name: z.union([z.string(), MediaModelsStringFilterSchema]).optional(),
    get bindings() {
      return MediaModelsBindingListRelationFilterSchema.optional();
    },
    and: z
      .array(z.lazy((): any => MediaModelsPlaylistWhereInputSchema))
      .optional(),
    or: z
      .array(z.lazy((): any => MediaModelsPlaylistWhereInputSchema))
      .optional(),
    not: z
      .array(z.lazy((): any => MediaModelsPlaylistWhereInputSchema))
      .optional(),
  })
  .register(z.globalRegistry, {
    description: "Playlist arguments for searching",
  });

/**
 * BindingListRelationFilter
 */
export const MediaModelsBindingListRelationFilterSchema = z.object({
  get some() {
    return MediaModelsBindingWhereInputSchema.optional();
  },
  get none() {
    return MediaModelsBindingWhereInputSchema.optional();
  },
  get every() {
    return MediaModelsBindingWhereInputSchema.optional();
  },
});

/**
 * PlaylistRelationFilter
 */
export const MediaModelsPlaylistRelationFilterSchema = z.object({
  is: MediaModelsPlaylistWhereInputSchema.optional(),
  isNot: MediaModelsPlaylistWhereInputSchema.optional(),
});

/**
 * BindingWhereInput
 *
 * Binding arguments for searching
 */
export const MediaModelsBindingWhereInputSchema = z
  .object({
    id: z.union([z.string(), MediaModelsStringFilterSchema]).optional(),
    playlistId: z.union([z.string(), MediaModelsStringFilterSchema]).optional(),
    mediaId: z.union([z.string(), MediaModelsStringFilterSchema]).optional(),
    rank: z.union([z.string(), MediaModelsStringFilterSchema]).optional(),
    playlist: MediaModelsPlaylistRelationFilterSchema.optional(),
    media: MediaModelsMediaRelationFilterSchema.optional(),
    and: z
      .array(z.lazy((): any => MediaModelsBindingWhereInputSchema))
      .optional(),
    or: z
      .array(z.lazy((): any => MediaModelsBindingWhereInputSchema))
      .optional(),
    not: z
      .array(z.lazy((): any => MediaModelsBindingWhereInputSchema))
      .optional(),
  })
  .register(z.globalRegistry, {
    description: "Binding arguments for searching",
  });

/**
 * PlaylistIncludeFromPlaylist
 *
 * Relational arguments for Playlist
 */
export const MediaModelsPlaylistIncludeFromPlaylistSchema = z
  .object({
    bindings: z
      .union([z.boolean(), MediaModelsFindManyBindingArgsFromPlaylistSchema])
      .optional(),
  })
  .register(z.globalRegistry, {
    description: "Relational arguments for Playlist",
  });

/**
 * PlaylistArgsFromBinding
 *
 * Arguments for Binding
 */
export const MediaModelsPlaylistArgsFromBindingSchema = z
  .object({
    include: MediaModelsPlaylistIncludeFromPlaylistSchema.optional(),
  })
  .register(z.globalRegistry, {
    description: "Arguments for Binding",
  });

/**
 * MediaInclude
 *
 * Media relational arguments
 */
export const MediaIncludeSchema = z
  .object({
    bindings: z
      .union([z.boolean(), MediaModelsFindManyBindingArgsFromMediaSchema])
      .optional(),
  })
  .register(z.globalRegistry, {
    description: "Media relational arguments",
  });

/**
 * Playlist
 *
 * Playlist data.
 */
export const MediaModelsPlaylistSchema = z
  .object({
    id: z.uuid().register(z.globalRegistry, {
      description: "Identifier of the playlist.",
    }),
    name: z.string().register(z.globalRegistry, {
      description: "Name of the playlist.",
    }),
    bindings: z.array(z.lazy((): any => MediaModelsBindingSchema)).nullable(),
  })
  .register(z.globalRegistry, {
    description: "Playlist data.",
  });

/**
 * Binding
 *
 * Binding data.
 */
export const MediaModelsBindingSchema = z
  .object({
    id: z.uuid().register(z.globalRegistry, {
      description: "Identifier of the binding.",
    }),
    playlistId: z.uuid().register(z.globalRegistry, {
      description: "Identifier of the playlist that the binding belongs to.",
    }),
    mediaId: z.uuid().register(z.globalRegistry, {
      description: "Identifier of the media that the binding belongs to.",
    }),
    rank: z.string().register(z.globalRegistry, {
      description: "Rank of the media in the binding.",
    }),
    playlist: MediaModelsPlaylistSchema.nullable(),
    media: z.lazy((): any => MediaModelsMediaSchema).nullable(),
  })
  .register(z.globalRegistry, {
    description: "Binding data.",
  });

/**
 * Media
 *
 * Media data.
 */
export const MediaModelsMediaSchema = z
  .object({
    id: z.uuid().register(z.globalRegistry, {
      description: "Identifier of the media.",
    }),
    name: z.string().register(z.globalRegistry, {
      description: "Name of the media.",
    }),
    bindings: z.array(MediaModelsBindingSchema).nullable(),
  })
  .register(z.globalRegistry, {
    description: "Media data.",
  });

/**
 * MediaList
 *
 * List of media.
 */
export const MediaModelsListResponseResultsSchema = z
  .object({
    count: z.int().register(z.globalRegistry, {
      description: "Total number of media that matched the query.",
    }),
    limit: z.int().nullable(),
    offset: z.int().nullable(),
    media: z.array(MediaModelsMediaSchema).register(z.globalRegistry, {
      description: "Media that matched the request.",
    }),
  })
  .register(z.globalRegistry, {
    description: "List of media.",
  });

export const MediaModelsListRequestWhereSchema =
  MediaModelsMediaWhereInputSchema.nullable();

export const MediaModelsListRequestIncludeSchema =
  MediaIncludeSchema.nullable();

export const MediaModelsGetRequestIncludeSchema = MediaIncludeSchema.nullable();

export const MediaModelsCreateRequestIncludeSchema =
  MediaIncludeSchema.nullable();

export const BindingsModelsUpdateRequestIncludeSchema = z
  .lazy(() => BindingIncludeSchema)
  .nullable();

/**
 * FindManyBindingArgsFromMedia
 *
 * Arguments for Media
 */
export const BindingsModelsFindManyBindingArgsFromMediaSchema = z
  .object({
    take: z.int().optional(),
    skip: z.int().optional(),
    orderBy: z
      .union([
        BindingsModelsBindingIdOrderByInputSchema,
        BindingsModelsBindingPlaylistIdOrderByInputSchema,
        BindingsModelsBindingMediaIdOrderByInputSchema,
        BindingsModelsBindingRankOrderByInputSchema,
        BindingsModelsBindingRelevanceOrderByInputSchema,
        z.array(
          z.union([
            BindingsModelsBindingIdOrderByInputSchema,
            BindingsModelsBindingPlaylistIdOrderByInputSchema,
            BindingsModelsBindingMediaIdOrderByInputSchema,
            BindingsModelsBindingRankOrderByInputSchema,
            BindingsModelsBindingRelevanceOrderByInputSchema,
          ]),
        ),
      ])
      .optional(),
    get where() {
      return BindingsModelsBindingWhereInputSchema.optional();
    },
    cursor: z
      .union([
        BindingsModelsBindingWhereUniqueIdInputSchema,
        BindingsModelsBindingCompoundplaylistIdRankKeySchema,
      ])
      .optional(),
    distinct: z
      .array(z.enum(["id", "playlistId", "mediaId", "rank"]))
      .optional(),
    get include() {
      return BindingsModelsBindingIncludeFromBindingSchema.optional();
    },
  })
  .register(z.globalRegistry, {
    description: "Arguments for Media",
  });

/**
 * BindingIncludeFromBinding
 *
 * Relational arguments for Binding
 */
export const BindingsModelsBindingIncludeFromBindingSchema = z
  .object({
    playlist: z
      .union([
        z.boolean(),
        z.lazy((): any => BindingsModelsPlaylistArgsFromBindingSchema),
      ])
      .optional(),
    media: z
      .union([
        z.boolean(),
        z.lazy((): any => BindingsModelsMediaArgsFromBindingSchema),
      ])
      .optional(),
  })
  .register(z.globalRegistry, {
    description: "Relational arguments for Binding",
  });

/**
 * MediaWhereInput
 *
 * Media arguments for searching
 */
export const BindingsModelsMediaWhereInputSchema = z
  .object({
    id: z.union([z.string(), BindingsModelsStringFilterSchema]).optional(),
    name: z.union([z.string(), BindingsModelsStringFilterSchema]).optional(),
    get bindings() {
      return BindingsModelsBindingListRelationFilterSchema.optional();
    },
    and: z
      .array(z.lazy((): any => BindingsModelsMediaWhereInputSchema))
      .optional(),
    or: z
      .array(z.lazy((): any => BindingsModelsMediaWhereInputSchema))
      .optional(),
    not: z
      .array(z.lazy((): any => BindingsModelsMediaWhereInputSchema))
      .optional(),
  })
  .register(z.globalRegistry, {
    description: "Media arguments for searching",
  });

/**
 * BindingWhereInput
 *
 * Binding arguments for searching
 */
export const BindingsModelsBindingWhereInputSchema = z
  .object({
    id: z.union([z.string(), BindingsModelsStringFilterSchema]).optional(),
    playlistId: z
      .union([z.string(), BindingsModelsStringFilterSchema])
      .optional(),
    mediaId: z.union([z.string(), BindingsModelsStringFilterSchema]).optional(),
    rank: z.union([z.string(), BindingsModelsStringFilterSchema]).optional(),
    playlist: z
      .lazy((): any => BindingsModelsPlaylistRelationFilterSchema)
      .optional(),
    media: z
      .lazy((): any => BindingsModelsMediaRelationFilterSchema)
      .optional(),
    and: z
      .array(z.lazy((): any => BindingsModelsBindingWhereInputSchema))
      .optional(),
    or: z
      .array(z.lazy((): any => BindingsModelsBindingWhereInputSchema))
      .optional(),
    not: z
      .array(z.lazy((): any => BindingsModelsBindingWhereInputSchema))
      .optional(),
  })
  .register(z.globalRegistry, {
    description: "Binding arguments for searching",
  });

/**
 * MediaRelationFilter
 */
export const BindingsModelsMediaRelationFilterSchema = z.object({
  is: BindingsModelsMediaWhereInputSchema.optional(),
  isNot: BindingsModelsMediaWhereInputSchema.optional(),
});

/**
 * BindingListRelationFilter
 */
export const BindingsModelsBindingListRelationFilterSchema = z.object({
  some: BindingsModelsBindingWhereInputSchema.optional(),
  none: BindingsModelsBindingWhereInputSchema.optional(),
  every: BindingsModelsBindingWhereInputSchema.optional(),
});

/**
 * PlaylistWhereInput
 *
 * Playlist arguments for searching
 */
export const BindingsModelsPlaylistWhereInputSchema = z
  .object({
    id: z.union([z.string(), BindingsModelsStringFilterSchema]).optional(),
    name: z.union([z.string(), BindingsModelsStringFilterSchema]).optional(),
    bindings: BindingsModelsBindingListRelationFilterSchema.optional(),
    and: z
      .array(z.lazy((): any => BindingsModelsPlaylistWhereInputSchema))
      .optional(),
    or: z
      .array(z.lazy((): any => BindingsModelsPlaylistWhereInputSchema))
      .optional(),
    not: z
      .array(z.lazy((): any => BindingsModelsPlaylistWhereInputSchema))
      .optional(),
  })
  .register(z.globalRegistry, {
    description: "Playlist arguments for searching",
  });

/**
 * PlaylistRelationFilter
 */
export const BindingsModelsPlaylistRelationFilterSchema = z.object({
  is: BindingsModelsPlaylistWhereInputSchema.optional(),
  isNot: BindingsModelsPlaylistWhereInputSchema.optional(),
});

/**
 * MediaIncludeFromMedia
 *
 * Relational arguments for Media
 */
export const BindingsModelsMediaIncludeFromMediaSchema = z
  .object({
    bindings: z
      .union([z.boolean(), BindingsModelsFindManyBindingArgsFromMediaSchema])
      .optional(),
  })
  .register(z.globalRegistry, {
    description: "Relational arguments for Media",
  });

/**
 * MediaArgsFromBinding
 *
 * Arguments for Binding
 */
export const BindingsModelsMediaArgsFromBindingSchema = z
  .object({
    include: BindingsModelsMediaIncludeFromMediaSchema.optional(),
  })
  .register(z.globalRegistry, {
    description: "Arguments for Binding",
  });

/**
 * PlaylistArgsFromBinding
 *
 * Arguments for Binding
 */
export const BindingsModelsPlaylistArgsFromBindingSchema = z
  .object({
    get include() {
      return BindingsModelsPlaylistIncludeFromPlaylistSchema.optional();
    },
  })
  .register(z.globalRegistry, {
    description: "Arguments for Binding",
  });

/**
 * FindManyBindingArgsFromPlaylist
 *
 * Arguments for Playlist
 */
export const BindingsModelsFindManyBindingArgsFromPlaylistSchema = z
  .object({
    take: z.int().optional(),
    skip: z.int().optional(),
    orderBy: z
      .union([
        BindingsModelsBindingIdOrderByInputSchema,
        BindingsModelsBindingPlaylistIdOrderByInputSchema,
        BindingsModelsBindingMediaIdOrderByInputSchema,
        BindingsModelsBindingRankOrderByInputSchema,
        BindingsModelsBindingRelevanceOrderByInputSchema,
        z.array(
          z.union([
            BindingsModelsBindingIdOrderByInputSchema,
            BindingsModelsBindingPlaylistIdOrderByInputSchema,
            BindingsModelsBindingMediaIdOrderByInputSchema,
            BindingsModelsBindingRankOrderByInputSchema,
            BindingsModelsBindingRelevanceOrderByInputSchema,
          ]),
        ),
      ])
      .optional(),
    where: BindingsModelsBindingWhereInputSchema.optional(),
    cursor: z
      .union([
        BindingsModelsBindingWhereUniqueIdInputSchema,
        BindingsModelsBindingCompoundplaylistIdRankKeySchema,
      ])
      .optional(),
    distinct: z
      .array(z.enum(["id", "playlistId", "mediaId", "rank"]))
      .optional(),
    include: BindingsModelsBindingIncludeFromBindingSchema.optional(),
  })
  .register(z.globalRegistry, {
    description: "Arguments for Playlist",
  });

/**
 * PlaylistIncludeFromPlaylist
 *
 * Relational arguments for Playlist
 */
export const BindingsModelsPlaylistIncludeFromPlaylistSchema = z
  .object({
    bindings: z
      .union([z.boolean(), BindingsModelsFindManyBindingArgsFromPlaylistSchema])
      .optional(),
  })
  .register(z.globalRegistry, {
    description: "Relational arguments for Playlist",
  });

/**
 * BindingInclude
 *
 * Binding relational arguments
 */
export const BindingIncludeSchema = z
  .object({
    playlist: z
      .union([z.boolean(), BindingsModelsPlaylistArgsFromBindingSchema])
      .optional(),
    media: z
      .union([z.boolean(), BindingsModelsMediaArgsFromBindingSchema])
      .optional(),
  })
  .register(z.globalRegistry, {
    description: "Binding relational arguments",
  });

/**
 * Playlist
 *
 * Playlist data.
 */
export const BindingsModelsPlaylistSchema = z
  .object({
    id: z.uuid().register(z.globalRegistry, {
      description: "Identifier of the playlist.",
    }),
    name: z.string().register(z.globalRegistry, {
      description: "Name of the playlist.",
    }),
    bindings: z
      .array(z.lazy((): any => BindingsModelsBindingSchema))
      .nullable(),
  })
  .register(z.globalRegistry, {
    description: "Playlist data.",
  });

/**
 * Binding
 *
 * Binding data.
 */
export const BindingsModelsBindingSchema = z
  .object({
    id: z.uuid().register(z.globalRegistry, {
      description: "Identifier of the binding.",
    }),
    playlistId: z.uuid().register(z.globalRegistry, {
      description: "Identifier of the playlist that the binding belongs to.",
    }),
    mediaId: z.uuid().register(z.globalRegistry, {
      description: "Identifier of the media that the binding belongs to.",
    }),
    rank: z.string().register(z.globalRegistry, {
      description: "Rank of the media in the binding.",
    }),
    playlist: BindingsModelsPlaylistSchema.nullable(),
    media: z.lazy((): any => BindingsModelsMediaSchema).nullable(),
  })
  .register(z.globalRegistry, {
    description: "Binding data.",
  });

/**
 * Media
 *
 * Media data.
 */
export const BindingsModelsMediaSchema = z
  .object({
    id: z.uuid().register(z.globalRegistry, {
      description: "Identifier of the media.",
    }),
    name: z.string().register(z.globalRegistry, {
      description: "Name of the media.",
    }),
    bindings: z.array(BindingsModelsBindingSchema).nullable(),
  })
  .register(z.globalRegistry, {
    description: "Media data.",
  });

/**
 * BindingList
 *
 * List of bindings.
 */
export const BindingsModelsListResponseResultsSchema = z
  .object({
    count: z.int().register(z.globalRegistry, {
      description: "Total number of bindings that matched the query.",
    }),
    limit: z.int().nullable(),
    offset: z.int().nullable(),
    bindings: z.array(BindingsModelsBindingSchema).register(z.globalRegistry, {
      description: "Bindings that matched the request.",
    }),
  })
  .register(z.globalRegistry, {
    description: "List of bindings.",
  });

export const BindingsModelsListRequestWhereSchema =
  BindingsModelsBindingWhereInputSchema.nullable();

export const BindingsModelsListRequestIncludeSchema =
  BindingIncludeSchema.nullable();

export const BindingsModelsGetRequestIncludeSchema =
  BindingIncludeSchema.nullable();

export const BindingsModelsCreateRequestIncludeSchema =
  BindingIncludeSchema.nullable();

/**
 * Playlist
 *
 * Playlist data.
 */
export const GetResponsePlaylistSchema = z
  .object({
    id: z.uuid().register(z.globalRegistry, {
      description: "Identifier of the playlist.",
    }),
    name: z.string().register(z.globalRegistry, {
      description: "Name of the playlist.",
    }),
    bindings: z.array(PlaylistsModelsBindingSchema).nullable(),
  })
  .register(z.globalRegistry, {
    description: "Playlist data.",
  });

/**
 * Media
 *
 * Media data.
 */
export const GetResponseMediaSchema = z
  .object({
    id: z.uuid().register(z.globalRegistry, {
      description: "Identifier of the media.",
    }),
    name: z.string().register(z.globalRegistry, {
      description: "Name of the media.",
    }),
    bindings: z.array(MediaModelsBindingSchema).nullable(),
  })
  .register(z.globalRegistry, {
    description: "Media data.",
  });

/**
 * Binding
 *
 * Binding data.
 */
export const GetResponseBindingSchema = z
  .object({
    id: z.uuid().register(z.globalRegistry, {
      description: "Identifier of the binding.",
    }),
    playlistId: z.uuid().register(z.globalRegistry, {
      description: "Identifier of the playlist that the binding belongs to.",
    }),
    mediaId: z.uuid().register(z.globalRegistry, {
      description: "Identifier of the media that the binding belongs to.",
    }),
    rank: z.string().register(z.globalRegistry, {
      description: "Rank of the media in the binding.",
    }),
    playlist: BindingsModelsPlaylistSchema.nullable(),
    media: BindingsModelsMediaSchema.nullable(),
  })
  .register(z.globalRegistry, {
    description: "Binding data.",
  });

export const BindingsIdDeleteRequestSchema = z.object({
  body: z.never().optional(),
  path: z.object({
    id: BindingsModelsDeleteRequestIdSchema,
  }),
  query: z.never().optional(),
});

/**
 * Request fulfilled, nothing follows
 */
export const BindingsIdDeleteResponseSchema = z
  .void()
  .register(z.globalRegistry, {
    description: "Request fulfilled, nothing follows",
  });

export const MediaIdDeleteRequestSchema = z.object({
  body: z.never().optional(),
  path: z.object({
    id: MediaModelsDeleteRequestIdSchema,
  }),
  query: z.never().optional(),
});

/**
 * Request fulfilled, nothing follows
 */
export const MediaIdDeleteResponseSchema = z.void().register(z.globalRegistry, {
  description: "Request fulfilled, nothing follows",
});

export const MediaIdContentDownloadRequestSchema = z.object({
  body: z.never().optional(),
  path: z.object({
    id: DownloadRequestIdSchema,
  }),
  query: z.never().optional(),
});

/**
 * Stream Response
 */
export const MediaIdContentDownloadResponseSchema = z
  .unknown()
  .register(z.globalRegistry, {
    description: "Stream Response",
  });

export const MediaIdContentHeaddownloadRequestSchema = z.object({
  body: z.never().optional(),
  path: z.object({
    id: DownloadRequestIdSchema,
  }),
  query: z.never().optional(),
});

export const MediaIdContentUploadRequestSchema = z.object({
  body: z.unknown(),
  path: z.object({
    id: UploadRequestIdSchema,
  }),
  query: z.never().optional(),
  headers: z.object({
    "content-type": z.union([UploadRequestTypeSchema, z.string()]),
  }),
});

/**
 * Request fulfilled, nothing follows
 */
export const MediaIdContentUploadResponseSchema = z
  .void()
  .register(z.globalRegistry, {
    description: "Request fulfilled, nothing follows",
  });

export const PingPingRequestSchema = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z.never().optional(),
});

/**
 * Request fulfilled, nothing follows
 */
export const PingPingResponseSchema = z.void().register(z.globalRegistry, {
  description: "Request fulfilled, nothing follows",
});

export const PingHeadpingRequestSchema = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z.never().optional(),
});

/**
 * Request fulfilled, nothing follows
 */
export const PingHeadpingResponseSchema = z.void().register(z.globalRegistry, {
  description: "Request fulfilled, nothing follows",
});

export const PlaylistsIdDeleteRequestSchema = z.object({
  body: z.never().optional(),
  path: z.object({
    id: PlaylistsModelsDeleteRequestIdSchema,
  }),
  query: z.never().optional(),
});

/**
 * Request fulfilled, nothing follows
 */
export const PlaylistsIdDeleteResponseSchema = z
  .void()
  .register(z.globalRegistry, {
    description: "Request fulfilled, nothing follows",
  });

export const PlaylistsIdM3Um3uRequestSchema = z.object({
  body: z.never().optional(),
  path: z.object({
    id: M3uRequestIdSchema,
  }),
  query: z.never().optional(),
});

/**
 * Request fulfilled, document follows
 */
export const PlaylistsIdM3Um3uResponseSchema = z
  .string()
  .register(z.globalRegistry, {
    description: "Request fulfilled, document follows",
  });

export const PlaylistsIdM3uHeadm3uRequestSchema = z.object({
  body: z.never().optional(),
  path: z.object({
    id: HeadM3uRequestIdSchema,
  }),
  query: z.never().optional(),
});

export const SseSubscribeRequestSchema = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z
    .object({
      types: z.union([SubscribeRequestTypesSchema, z.string()]).nullish(),
    })
    .optional(),
});

/**
 * Request fulfilled, stream of Server-Sent Events follows
 */
export const SseSubscribeResponseSchema = z
  .string()
  .register(z.globalRegistry, {
    description: "Request fulfilled, stream of Server-Sent Events follows",
  });

export const TestTestRequestSchema = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z
    .object({
      parameters: z.union([TestRequestParametersSchema, z.string()]).nullish(),
    })
    .optional(),
});

/**
 * Request fulfilled, document follows
 */
export const TestTestResponseSchema = TestResponseResultSchema;

export const BindingsListRequestSchema = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z
    .object({
      limit: z
        .union([BindingsModelsListRequestLimitSchema, z.string()])
        .nullish(),
      offset: z
        .union([BindingsModelsListRequestOffsetSchema, z.string()])
        .nullish(),
      where: z
        .union([BindingsModelsListRequestWhereSchema, z.string()])
        .nullish(),
      include: z
        .union([BindingsModelsListRequestIncludeSchema, z.string()])
        .nullish(),
      order: z
        .union([BindingsModelsListRequestOrderSchema, z.string()])
        .nullish(),
    })
    .optional(),
});

/**
 * Request fulfilled, document follows
 */
export const BindingsListResponseSchema =
  BindingsModelsListResponseResultsSchema;

export const BindingsCreateRequestSchema = z.object({
  body: BindingsModelsCreateRequestDataSchema,
  path: z.never().optional(),
  query: z
    .object({
      include: z
        .union([BindingsModelsCreateRequestIncludeSchema, z.string()])
        .nullish(),
    })
    .optional(),
});

/**
 * Document created, URL follows
 */
export const BindingsCreateResponseSchema = BindingsModelsBindingSchema;

export const BindingsIdGetRequestSchema = z.object({
  body: z.never().optional(),
  path: z.object({
    id: BindingsModelsGetRequestIdSchema,
  }),
  query: z
    .object({
      include: z
        .union([BindingsModelsGetRequestIncludeSchema, z.string()])
        .nullish(),
    })
    .optional(),
});

/**
 * Request fulfilled, document follows
 */
export const BindingsIdGetResponseSchema = GetResponseBindingSchema;

export const BindingsIdUpdateRequestSchema = z.object({
  body: BindingsModelsUpdateRequestDataSchema,
  path: z.object({
    id: BindingsModelsUpdateRequestIdSchema,
  }),
  query: z
    .object({
      include: z
        .union([BindingsModelsUpdateRequestIncludeSchema, z.string()])
        .nullish(),
    })
    .optional(),
});

/**
 * Request fulfilled, document follows
 */
export const BindingsIdUpdateResponseSchema = BindingsModelsBindingSchema;

export const MediaListRequestSchema = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z
    .object({
      limit: z.union([MediaModelsListRequestLimitSchema, z.string()]).nullish(),
      offset: z
        .union([MediaModelsListRequestOffsetSchema, z.string()])
        .nullish(),
      where: z.union([MediaModelsListRequestWhereSchema, z.string()]).nullish(),
      include: z
        .union([MediaModelsListRequestIncludeSchema, z.string()])
        .nullish(),
      order: z.union([MediaModelsListRequestOrderSchema, z.string()]).nullish(),
    })
    .optional(),
});

/**
 * Request fulfilled, document follows
 */
export const MediaListResponseSchema = MediaModelsListResponseResultsSchema;

export const MediaCreateRequestSchema = z.object({
  body: MediaModelsCreateRequestDataSchema,
  path: z.never().optional(),
  query: z
    .object({
      include: z
        .union([MediaModelsCreateRequestIncludeSchema, z.string()])
        .nullish(),
    })
    .optional(),
});

/**
 * Document created, URL follows
 */
export const MediaCreateResponseSchema = MediaModelsMediaSchema;

export const MediaIdGetRequestSchema = z.object({
  body: z.never().optional(),
  path: z.object({
    id: MediaModelsGetRequestIdSchema,
  }),
  query: z
    .object({
      include: z
        .union([MediaModelsGetRequestIncludeSchema, z.string()])
        .nullish(),
    })
    .optional(),
});

/**
 * Request fulfilled, document follows
 */
export const MediaIdGetResponseSchema = GetResponseMediaSchema;

export const MediaIdUpdateRequestSchema = z.object({
  body: MediaModelsUpdateRequestDataSchema,
  path: z.object({
    id: MediaModelsUpdateRequestIdSchema,
  }),
  query: z
    .object({
      include: z
        .union([MediaModelsUpdateRequestIncludeSchema, z.string()])
        .nullish(),
    })
    .optional(),
});

/**
 * Request fulfilled, document follows
 */
export const MediaIdUpdateResponseSchema = MediaModelsMediaSchema;

export const PlaylistsListRequestSchema = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z
    .object({
      limit: z
        .union([PlaylistsModelsListRequestLimitSchema, z.string()])
        .nullish(),
      offset: z
        .union([PlaylistsModelsListRequestOffsetSchema, z.string()])
        .nullish(),
      where: z
        .union([PlaylistsModelsListRequestWhereSchema, z.string()])
        .nullish(),
      include: z
        .union([PlaylistsModelsListRequestIncludeSchema, z.string()])
        .nullish(),
      order: z
        .union([PlaylistsModelsListRequestOrderSchema, z.string()])
        .nullish(),
    })
    .optional(),
});

/**
 * Request fulfilled, document follows
 */
export const PlaylistsListResponseSchema =
  PlaylistsModelsListResponseResultsSchema;

export const PlaylistsCreateRequestSchema = z.object({
  body: PlaylistsModelsCreateRequestDataSchema,
  path: z.never().optional(),
  query: z
    .object({
      include: z
        .union([PlaylistsModelsCreateRequestIncludeSchema, z.string()])
        .nullish(),
    })
    .optional(),
});

/**
 * Document created, URL follows
 */
export const PlaylistsCreateResponseSchema = PlaylistsModelsPlaylistSchema;

export const PlaylistsIdGetRequestSchema = z.object({
  body: z.never().optional(),
  path: z.object({
    id: PlaylistsModelsGetRequestIdSchema,
  }),
  query: z
    .object({
      include: z
        .union([PlaylistsModelsGetRequestIncludeSchema, z.string()])
        .nullish(),
    })
    .optional(),
});

/**
 * Request fulfilled, document follows
 */
export const PlaylistsIdGetResponseSchema = GetResponsePlaylistSchema;

export const PlaylistsIdUpdateRequestSchema = z.object({
  body: PlaylistsModelsUpdateRequestDataSchema,
  path: z.object({
    id: PlaylistsModelsUpdateRequestIdSchema,
  }),
  query: z
    .object({
      include: z
        .union([PlaylistsModelsUpdateRequestIncludeSchema, z.string()])
        .nullish(),
    })
    .optional(),
});

/**
 * Request fulfilled, document follows
 */
export const PlaylistsIdUpdateResponseSchema = PlaylistsModelsPlaylistSchema;
