// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

/**
 * _Binding_rank_OrderByInput
 */
export type PlaylistsModelsBindingRankOrderByInput = {
  /**
   * Rank
   */
  rank: "asc" | "desc";
};

/**
 * _Binding_playlistId_OrderByInput
 */
export type PlaylistsModelsBindingPlaylistIdOrderByInput = {
  /**
   * Playlistid
   */
  playlistId: "asc" | "desc";
};

/**
 * _Binding_mediaId_OrderByInput
 */
export type PlaylistsModelsBindingMediaIdOrderByInput = {
  /**
   * Mediaid
   */
  mediaId: "asc" | "desc";
};

/**
 * _Binding_id_OrderByInput
 */
export type PlaylistsModelsBindingIdOrderByInput = {
  /**
   * Id
   */
  id: "asc" | "desc";
};

/**
 * _Binding_RelevanceOrderByInput
 */
export type PlaylistsModelsBindingRelevanceOrderByInput = {
  _relevance: PlaylistsModelsBindingRelevanceInner;
};

/**
 * _Binding_RelevanceInner
 */
export type PlaylistsModelsBindingRelevanceInner = {
  /**
   * Fields
   */
  fields: Array<"id" | "playlistId" | "mediaId" | "rank">;
  /**
   * Search
   */
  search: string;
  /**
   * Sort
   */
  sort: "asc" | "desc";
};

/**
 * _BindingWhereUnique_id_Input
 */
export type PlaylistsModelsBindingWhereUniqueIdInput = {
  /**
   * Id
   */
  id: string;
};

/**
 * _BindingCompoundplaylistId_rankKeyInner
 */
export type PlaylistsModelsBindingCompoundplaylistIdRankKeyInner = {
  /**
   * Playlistid
   */
  playlistId: string;
  /**
   * Rank
   */
  rank: string;
};

/**
 * _BindingCompoundplaylistId_rankKey
 */
export type PlaylistsModelsBindingCompoundplaylistIdRankKey = {
  playlistidRank: PlaylistsModelsBindingCompoundplaylistIdRankKeyInner;
};

export type PlaylistsModelsUpdateRequestInclude = PlaylistInclude | null;

/**
 * FindManyBindingArgsFromMedia
 *
 * Arguments for Media
 */
export type PlaylistsModelsFindManyBindingArgsFromMedia = {
  /**
   * Take
   */
  take?: number;
  /**
   * Skip
   */
  skip?: number;
  /**
   * Orderby
   */
  orderBy?:
    | PlaylistsModelsBindingIdOrderByInput
    | PlaylistsModelsBindingPlaylistIdOrderByInput
    | PlaylistsModelsBindingMediaIdOrderByInput
    | PlaylistsModelsBindingRankOrderByInput
    | PlaylistsModelsBindingRelevanceOrderByInput
    | Array<
        | PlaylistsModelsBindingIdOrderByInput
        | PlaylistsModelsBindingPlaylistIdOrderByInput
        | PlaylistsModelsBindingMediaIdOrderByInput
        | PlaylistsModelsBindingRankOrderByInput
        | PlaylistsModelsBindingRelevanceOrderByInput
      >;
  where?: PlaylistsModelsBindingWhereInput;
  /**
   * Cursor
   */
  cursor?:
    | PlaylistsModelsBindingWhereUniqueIdInput
    | PlaylistsModelsBindingCompoundplaylistIdRankKey;
  /**
   * Distinct
   */
  distinct?: Array<"id" | "playlistId" | "mediaId" | "rank">;
  include?: PlaylistsModelsBindingIncludeFromBinding;
};

/**
 * BindingIncludeFromBinding
 *
 * Relational arguments for Binding
 */
export type PlaylistsModelsBindingIncludeFromBinding = {
  /**
   * Playlist
   */
  playlist?: boolean | PlaylistsModelsPlaylistArgsFromBinding;
  /**
   * Media
   */
  media?: boolean | PlaylistsModelsMediaArgsFromBinding;
};

/**
 * BindingListRelationFilter
 */
export type PlaylistsModelsBindingListRelationFilter = {
  some?: PlaylistsModelsBindingWhereInput;
  none?: PlaylistsModelsBindingWhereInput;
  every?: PlaylistsModelsBindingWhereInput;
};

/**
 * MediaWhereInput
 *
 * Media arguments for searching
 */
export type PlaylistsModelsMediaWhereInput = {
  /**
   * Id
   */
  id?: string | PlaylistsModelsStringFilter;
  /**
   * Name
   */
  name?: string | PlaylistsModelsStringFilter;
  bindings?: PlaylistsModelsBindingListRelationFilter;
  /**
   * And
   */
  and?: Array<PlaylistsModelsMediaWhereInput>;
  /**
   * Or
   */
  or?: Array<PlaylistsModelsMediaWhereInput>;
  /**
   * Not
   */
  not?: Array<PlaylistsModelsMediaWhereInput>;
};

/**
 * StringFilter
 */
export type PlaylistsModelsStringFilter = {
  /**
   * Equals
   */
  equals?: string;
  /**
   * Notin
   */
  notIn?: Array<string>;
  /**
   * Lt
   */
  lt?: string;
  /**
   * Lte
   */
  lte?: string;
  /**
   * Gt
   */
  gt?: string;
  /**
   * Gte
   */
  gte?: string;
  /**
   * Contains
   */
  contains?: string;
  /**
   * Startswith
   */
  startswith?: string;
  /**
   * Endswith
   */
  endswith?: string;
  /**
   * In
   */
  in?: Array<string>;
  /**
   * Not
   */
  not?: string | PlaylistsModelsStringFilter;
  /**
   * Mode
   */
  mode?: "default" | "insensitive";
  /**
   * Search
   */
  search?: string;
};

/**
 * MediaRelationFilter
 */
export type PlaylistsModelsMediaRelationFilter = {
  is?: PlaylistsModelsMediaWhereInput;
  isNot?: PlaylistsModelsMediaWhereInput;
};

/**
 * PlaylistWhereInput
 *
 * Playlist arguments for searching
 */
export type PlaylistsModelsPlaylistWhereInput = {
  /**
   * Id
   */
  id?: string | PlaylistsModelsStringFilter;
  /**
   * Name
   */
  name?: string | PlaylistsModelsStringFilter;
  bindings?: PlaylistsModelsBindingListRelationFilter;
  /**
   * And
   */
  and?: Array<PlaylistsModelsPlaylistWhereInput>;
  /**
   * Or
   */
  or?: Array<PlaylistsModelsPlaylistWhereInput>;
  /**
   * Not
   */
  not?: Array<PlaylistsModelsPlaylistWhereInput>;
};

/**
 * PlaylistRelationFilter
 */
export type PlaylistsModelsPlaylistRelationFilter = {
  is?: PlaylistsModelsPlaylistWhereInput;
  isNot?: PlaylistsModelsPlaylistWhereInput;
};

/**
 * BindingWhereInput
 *
 * Binding arguments for searching
 */
export type PlaylistsModelsBindingWhereInput = {
  /**
   * Id
   */
  id?: string | PlaylistsModelsStringFilter;
  /**
   * Playlistid
   */
  playlistId?: string | PlaylistsModelsStringFilter;
  /**
   * Mediaid
   */
  mediaId?: string | PlaylistsModelsStringFilter;
  /**
   * Rank
   */
  rank?: string | PlaylistsModelsStringFilter;
  playlist?: PlaylistsModelsPlaylistRelationFilter;
  media?: PlaylistsModelsMediaRelationFilter;
  /**
   * And
   */
  and?: Array<PlaylistsModelsBindingWhereInput>;
  /**
   * Or
   */
  or?: Array<PlaylistsModelsBindingWhereInput>;
  /**
   * Not
   */
  not?: Array<PlaylistsModelsBindingWhereInput>;
};

/**
 * MediaIncludeFromMedia
 *
 * Relational arguments for Media
 */
export type PlaylistsModelsMediaIncludeFromMedia = {
  /**
   * Bindings
   */
  bindings?: boolean | PlaylistsModelsFindManyBindingArgsFromMedia;
};

/**
 * MediaArgsFromBinding
 *
 * Arguments for Binding
 */
export type PlaylistsModelsMediaArgsFromBinding = {
  include?: PlaylistsModelsMediaIncludeFromMedia;
};

/**
 * FindManyBindingArgsFromPlaylist
 *
 * Arguments for Playlist
 */
export type PlaylistsModelsFindManyBindingArgsFromPlaylist = {
  /**
   * Take
   */
  take?: number;
  /**
   * Skip
   */
  skip?: number;
  /**
   * Orderby
   */
  orderBy?:
    | PlaylistsModelsBindingIdOrderByInput
    | PlaylistsModelsBindingPlaylistIdOrderByInput
    | PlaylistsModelsBindingMediaIdOrderByInput
    | PlaylistsModelsBindingRankOrderByInput
    | PlaylistsModelsBindingRelevanceOrderByInput
    | Array<
        | PlaylistsModelsBindingIdOrderByInput
        | PlaylistsModelsBindingPlaylistIdOrderByInput
        | PlaylistsModelsBindingMediaIdOrderByInput
        | PlaylistsModelsBindingRankOrderByInput
        | PlaylistsModelsBindingRelevanceOrderByInput
      >;
  where?: PlaylistsModelsBindingWhereInput;
  /**
   * Cursor
   */
  cursor?:
    | PlaylistsModelsBindingWhereUniqueIdInput
    | PlaylistsModelsBindingCompoundplaylistIdRankKey;
  /**
   * Distinct
   */
  distinct?: Array<"id" | "playlistId" | "mediaId" | "rank">;
  include?: PlaylistsModelsBindingIncludeFromBinding;
};

/**
 * PlaylistIncludeFromPlaylist
 *
 * Relational arguments for Playlist
 */
export type PlaylistsModelsPlaylistIncludeFromPlaylist = {
  /**
   * Bindings
   */
  bindings?: boolean | PlaylistsModelsFindManyBindingArgsFromPlaylist;
};

/**
 * PlaylistArgsFromBinding
 *
 * Arguments for Binding
 */
export type PlaylistsModelsPlaylistArgsFromBinding = {
  include?: PlaylistsModelsPlaylistIncludeFromPlaylist;
};

/**
 * PlaylistInclude
 *
 * Playlist relational arguments
 */
export type PlaylistInclude = {
  /**
   * Bindings
   */
  bindings?: boolean | PlaylistsModelsFindManyBindingArgsFromPlaylist;
};

export type PlaylistsModelsUpdateRequestId = string;

/**
 * PlaylistUpdateManyMutationInput
 *
 * Arguments for updating many records
 */
export type PlaylistsModelsUpdateRequestData = {
  /**
   * Id
   */
  id?: string;
  /**
   * Name
   */
  name?: string;
};

/**
 * Playlist
 *
 * Playlist data.
 */
export type PlaylistsModelsPlaylist = {
  /**
   * Id
   *
   * Identifier of the playlist.
   */
  id: string;
  /**
   * Name
   *
   * Name of the playlist.
   */
  name: string;
  /**
   * Bindings
   *
   * Bindings that the playlist belongs to.
   */
  bindings: Array<PlaylistsModelsBinding> | null;
};

/**
 * Media
 *
 * Media data.
 */
export type PlaylistsModelsMedia = {
  /**
   * Id
   *
   * Identifier of the media.
   */
  id: string;
  /**
   * Name
   *
   * Name of the media.
   */
  name: string;
  /**
   * Bindings
   *
   * Bindings that the media belongs to.
   */
  bindings: Array<PlaylistsModelsBinding> | null;
};

/**
 * Binding
 *
 * Binding data.
 */
export type PlaylistsModelsBinding = {
  /**
   * Id
   *
   * Identifier of the binding.
   */
  id: string;
  /**
   * Playlistid
   *
   * Identifier of the playlist that the binding belongs to.
   */
  playlistId: string;
  /**
   * Mediaid
   *
   * Identifier of the media that the binding belongs to.
   */
  mediaId: string;
  /**
   * Rank
   *
   * Rank of the media in the binding.
   */
  rank: string;
  /**
   * Playlist that the binding belongs to.
   */
  playlist: PlaylistsModelsPlaylist | null;
  /**
   * Media that the binding belongs to.
   */
  media: PlaylistsModelsMedia | null;
};

/**
 * PlaylistList
 *
 * List of playlists.
 */
export type PlaylistsModelsListResponseResults = {
  /**
   * Count
   *
   * Total number of playlists that matched the query.
   */
  count: number;
  /**
   * Limit
   *
   * Maximum number of returned playlists.
   */
  limit: number | null;
  /**
   * Offset
   *
   * Number of playlists skipped.
   */
  offset: number | null;
  /**
   * Playlists
   *
   * Playlists that matched the request.
   */
  playlists: Array<PlaylistsModelsPlaylist>;
};

export type PlaylistsModelsListRequestWhere =
  PlaylistsModelsPlaylistWhereInput | null;

export type PlaylistsModelsListRequestOrder =
  | PlaylistOrderByInput
  | Array<PlaylistOrderByInput>
  | null;

/**
 * _Playlist_name_OrderByInput
 */
export type PlaylistNameOrderByInput = {
  /**
   * Name
   */
  name: "asc" | "desc";
};

/**
 * _Playlist_id_OrderByInput
 */
export type PlaylistIdOrderByInput = {
  /**
   * Id
   */
  id: "asc" | "desc";
};

export type PlaylistOrderByInput =
  | PlaylistIdOrderByInput
  | PlaylistNameOrderByInput;

export type PlaylistsModelsListRequestOffset = number | null;

export type PlaylistsModelsListRequestLimit = number | null;

export type PlaylistsModelsListRequestInclude = PlaylistInclude | null;

export type PlaylistsModelsGetRequestInclude = PlaylistInclude | null;

export type PlaylistsModelsGetRequestId = string;

export type PlaylistsModelsDeleteRequestId = string;

export type PlaylistsModelsCreateRequestInclude = PlaylistInclude | null;

/**
 * PlaylistCreateWithoutRelationsInput
 *
 * Required arguments to the Playlist create method, without relations
 */
export type PlaylistsModelsCreateRequestData = {
  /**
   * Id
   */
  id?: string;
  /**
   * Name
   */
  name: string;
};

/**
 * _Binding_rank_OrderByInput
 */
export type MediaModelsBindingRankOrderByInput = {
  /**
   * Rank
   */
  rank: "asc" | "desc";
};

/**
 * _Binding_playlistId_OrderByInput
 */
export type MediaModelsBindingPlaylistIdOrderByInput = {
  /**
   * Playlistid
   */
  playlistId: "asc" | "desc";
};

/**
 * _Binding_mediaId_OrderByInput
 */
export type MediaModelsBindingMediaIdOrderByInput = {
  /**
   * Mediaid
   */
  mediaId: "asc" | "desc";
};

/**
 * _Binding_id_OrderByInput
 */
export type MediaModelsBindingIdOrderByInput = {
  /**
   * Id
   */
  id: "asc" | "desc";
};

/**
 * _Binding_RelevanceOrderByInput
 */
export type MediaModelsBindingRelevanceOrderByInput = {
  _relevance: MediaModelsBindingRelevanceInner;
};

/**
 * _Binding_RelevanceInner
 */
export type MediaModelsBindingRelevanceInner = {
  /**
   * Fields
   */
  fields: Array<"id" | "playlistId" | "mediaId" | "rank">;
  /**
   * Search
   */
  search: string;
  /**
   * Sort
   */
  sort: "asc" | "desc";
};

/**
 * _BindingWhereUnique_id_Input
 */
export type MediaModelsBindingWhereUniqueIdInput = {
  /**
   * Id
   */
  id: string;
};

/**
 * _BindingCompoundplaylistId_rankKeyInner
 */
export type MediaModelsBindingCompoundplaylistIdRankKeyInner = {
  /**
   * Playlistid
   */
  playlistId: string;
  /**
   * Rank
   */
  rank: string;
};

/**
 * _BindingCompoundplaylistId_rankKey
 */
export type MediaModelsBindingCompoundplaylistIdRankKey = {
  playlistidRank: MediaModelsBindingCompoundplaylistIdRankKeyInner;
};

export type MediaModelsUpdateRequestInclude = MediaInclude | null;

/**
 * MediaIncludeFromMedia
 *
 * Relational arguments for Media
 */
export type MediaModelsMediaIncludeFromMedia = {
  /**
   * Bindings
   */
  bindings?: boolean | MediaModelsFindManyBindingArgsFromMedia;
};

/**
 * FindManyBindingArgsFromMedia
 *
 * Arguments for Media
 */
export type MediaModelsFindManyBindingArgsFromMedia = {
  /**
   * Take
   */
  take?: number;
  /**
   * Skip
   */
  skip?: number;
  /**
   * Orderby
   */
  orderBy?:
    | MediaModelsBindingIdOrderByInput
    | MediaModelsBindingPlaylistIdOrderByInput
    | MediaModelsBindingMediaIdOrderByInput
    | MediaModelsBindingRankOrderByInput
    | MediaModelsBindingRelevanceOrderByInput
    | Array<
        | MediaModelsBindingIdOrderByInput
        | MediaModelsBindingPlaylistIdOrderByInput
        | MediaModelsBindingMediaIdOrderByInput
        | MediaModelsBindingRankOrderByInput
        | MediaModelsBindingRelevanceOrderByInput
      >;
  where?: MediaModelsBindingWhereInput;
  /**
   * Cursor
   */
  cursor?:
    | MediaModelsBindingWhereUniqueIdInput
    | MediaModelsBindingCompoundplaylistIdRankKey;
  /**
   * Distinct
   */
  distinct?: Array<"id" | "playlistId" | "mediaId" | "rank">;
  include?: MediaModelsBindingIncludeFromBinding;
};

/**
 * MediaArgsFromBinding
 *
 * Arguments for Binding
 */
export type MediaModelsMediaArgsFromBinding = {
  include?: MediaModelsMediaIncludeFromMedia;
};

/**
 * FindManyBindingArgsFromPlaylist
 *
 * Arguments for Playlist
 */
export type MediaModelsFindManyBindingArgsFromPlaylist = {
  /**
   * Take
   */
  take?: number;
  /**
   * Skip
   */
  skip?: number;
  /**
   * Orderby
   */
  orderBy?:
    | MediaModelsBindingIdOrderByInput
    | MediaModelsBindingPlaylistIdOrderByInput
    | MediaModelsBindingMediaIdOrderByInput
    | MediaModelsBindingRankOrderByInput
    | MediaModelsBindingRelevanceOrderByInput
    | Array<
        | MediaModelsBindingIdOrderByInput
        | MediaModelsBindingPlaylistIdOrderByInput
        | MediaModelsBindingMediaIdOrderByInput
        | MediaModelsBindingRankOrderByInput
        | MediaModelsBindingRelevanceOrderByInput
      >;
  where?: MediaModelsBindingWhereInput;
  /**
   * Cursor
   */
  cursor?:
    | MediaModelsBindingWhereUniqueIdInput
    | MediaModelsBindingCompoundplaylistIdRankKey;
  /**
   * Distinct
   */
  distinct?: Array<"id" | "playlistId" | "mediaId" | "rank">;
  include?: MediaModelsBindingIncludeFromBinding;
};

/**
 * BindingIncludeFromBinding
 *
 * Relational arguments for Binding
 */
export type MediaModelsBindingIncludeFromBinding = {
  /**
   * Playlist
   */
  playlist?: boolean | MediaModelsPlaylistArgsFromBinding;
  /**
   * Media
   */
  media?: boolean | MediaModelsMediaArgsFromBinding;
};

/**
 * MediaWhereInput
 *
 * Media arguments for searching
 */
export type MediaModelsMediaWhereInput = {
  /**
   * Id
   */
  id?: string | MediaModelsStringFilter;
  /**
   * Name
   */
  name?: string | MediaModelsStringFilter;
  bindings?: MediaModelsBindingListRelationFilter;
  /**
   * And
   */
  and?: Array<MediaModelsMediaWhereInput>;
  /**
   * Or
   */
  or?: Array<MediaModelsMediaWhereInput>;
  /**
   * Not
   */
  not?: Array<MediaModelsMediaWhereInput>;
};

/**
 * MediaRelationFilter
 */
export type MediaModelsMediaRelationFilter = {
  is?: MediaModelsMediaWhereInput;
  isNot?: MediaModelsMediaWhereInput;
};

/**
 * PlaylistWhereInput
 *
 * Playlist arguments for searching
 */
export type MediaModelsPlaylistWhereInput = {
  /**
   * Id
   */
  id?: string | MediaModelsStringFilter;
  /**
   * Name
   */
  name?: string | MediaModelsStringFilter;
  bindings?: MediaModelsBindingListRelationFilter;
  /**
   * And
   */
  and?: Array<MediaModelsPlaylistWhereInput>;
  /**
   * Or
   */
  or?: Array<MediaModelsPlaylistWhereInput>;
  /**
   * Not
   */
  not?: Array<MediaModelsPlaylistWhereInput>;
};

/**
 * BindingListRelationFilter
 */
export type MediaModelsBindingListRelationFilter = {
  some?: MediaModelsBindingWhereInput;
  none?: MediaModelsBindingWhereInput;
  every?: MediaModelsBindingWhereInput;
};

/**
 * PlaylistRelationFilter
 */
export type MediaModelsPlaylistRelationFilter = {
  is?: MediaModelsPlaylistWhereInput;
  isNot?: MediaModelsPlaylistWhereInput;
};

/**
 * StringFilter
 */
export type MediaModelsStringFilter = {
  /**
   * Equals
   */
  equals?: string;
  /**
   * Notin
   */
  notIn?: Array<string>;
  /**
   * Lt
   */
  lt?: string;
  /**
   * Lte
   */
  lte?: string;
  /**
   * Gt
   */
  gt?: string;
  /**
   * Gte
   */
  gte?: string;
  /**
   * Contains
   */
  contains?: string;
  /**
   * Startswith
   */
  startswith?: string;
  /**
   * Endswith
   */
  endswith?: string;
  /**
   * In
   */
  in?: Array<string>;
  /**
   * Not
   */
  not?: string | MediaModelsStringFilter;
  /**
   * Mode
   */
  mode?: "default" | "insensitive";
  /**
   * Search
   */
  search?: string;
};

/**
 * BindingWhereInput
 *
 * Binding arguments for searching
 */
export type MediaModelsBindingWhereInput = {
  /**
   * Id
   */
  id?: string | MediaModelsStringFilter;
  /**
   * Playlistid
   */
  playlistId?: string | MediaModelsStringFilter;
  /**
   * Mediaid
   */
  mediaId?: string | MediaModelsStringFilter;
  /**
   * Rank
   */
  rank?: string | MediaModelsStringFilter;
  playlist?: MediaModelsPlaylistRelationFilter;
  media?: MediaModelsMediaRelationFilter;
  /**
   * And
   */
  and?: Array<MediaModelsBindingWhereInput>;
  /**
   * Or
   */
  or?: Array<MediaModelsBindingWhereInput>;
  /**
   * Not
   */
  not?: Array<MediaModelsBindingWhereInput>;
};

/**
 * PlaylistIncludeFromPlaylist
 *
 * Relational arguments for Playlist
 */
export type MediaModelsPlaylistIncludeFromPlaylist = {
  /**
   * Bindings
   */
  bindings?: boolean | MediaModelsFindManyBindingArgsFromPlaylist;
};

/**
 * PlaylistArgsFromBinding
 *
 * Arguments for Binding
 */
export type MediaModelsPlaylistArgsFromBinding = {
  include?: MediaModelsPlaylistIncludeFromPlaylist;
};

/**
 * MediaInclude
 *
 * Media relational arguments
 */
export type MediaInclude = {
  /**
   * Bindings
   */
  bindings?: boolean | MediaModelsFindManyBindingArgsFromMedia;
};

export type MediaModelsUpdateRequestId = string;

/**
 * MediaUpdateManyMutationInput
 *
 * Arguments for updating many records
 */
export type MediaModelsUpdateRequestData = {
  /**
   * Id
   */
  id?: string;
  /**
   * Name
   */
  name?: string;
};

/**
 * Playlist
 *
 * Playlist data.
 */
export type MediaModelsPlaylist = {
  /**
   * Id
   *
   * Identifier of the playlist.
   */
  id: string;
  /**
   * Name
   *
   * Name of the playlist.
   */
  name: string;
  /**
   * Bindings
   *
   * Bindings that the playlist belongs to.
   */
  bindings: Array<MediaModelsBinding> | null;
};

/**
 * Binding
 *
 * Binding data.
 */
export type MediaModelsBinding = {
  /**
   * Id
   *
   * Identifier of the binding.
   */
  id: string;
  /**
   * Playlistid
   *
   * Identifier of the playlist that the binding belongs to.
   */
  playlistId: string;
  /**
   * Mediaid
   *
   * Identifier of the media that the binding belongs to.
   */
  mediaId: string;
  /**
   * Rank
   *
   * Rank of the media in the binding.
   */
  rank: string;
  /**
   * Playlist that the binding belongs to.
   */
  playlist: MediaModelsPlaylist | null;
  /**
   * Media that the binding belongs to.
   */
  media: MediaModelsMedia | null;
};

/**
 * Media
 *
 * Media data.
 */
export type MediaModelsMedia = {
  /**
   * Id
   *
   * Identifier of the media.
   */
  id: string;
  /**
   * Name
   *
   * Name of the media.
   */
  name: string;
  /**
   * Bindings
   *
   * Bindings that the media belongs to.
   */
  bindings: Array<MediaModelsBinding> | null;
};

/**
 * MediaList
 *
 * List of media.
 */
export type MediaModelsListResponseResults = {
  /**
   * Count
   *
   * Total number of media that matched the query.
   */
  count: number;
  /**
   * Limit
   *
   * Maximum number of returned media.
   */
  limit: number | null;
  /**
   * Offset
   *
   * Number of media skipped.
   */
  offset: number | null;
  /**
   * Media
   *
   * Media that matched the request.
   */
  media: Array<MediaModelsMedia>;
};

export type MediaModelsListRequestWhere = MediaModelsMediaWhereInput | null;

export type MediaModelsListRequestOrder =
  | MediaOrderByInput
  | Array<MediaOrderByInput>
  | null;

/**
 * _Media_name_OrderByInput
 */
export type MediaNameOrderByInput = {
  /**
   * Name
   */
  name: "asc" | "desc";
};

/**
 * _Media_id_OrderByInput
 */
export type MediaIdOrderByInput = {
  /**
   * Id
   */
  id: "asc" | "desc";
};

export type MediaOrderByInput = MediaIdOrderByInput | MediaNameOrderByInput;

export type MediaModelsListRequestOffset = number | null;

export type MediaModelsListRequestLimit = number | null;

export type MediaModelsListRequestInclude = MediaInclude | null;

export type MediaModelsGetRequestInclude = MediaInclude | null;

export type MediaModelsGetRequestId = string;

export type MediaModelsDeleteRequestId = string;

export type MediaModelsCreateRequestInclude = MediaInclude | null;

/**
 * MediaCreateWithoutRelationsInput
 *
 * Required arguments to the Media create method, without relations
 */
export type MediaModelsCreateRequestData = {
  /**
   * Id
   */
  id?: string;
  /**
   * Name
   */
  name: string;
};

/**
 * _Binding_rank_OrderByInput
 */
export type BindingsModelsBindingRankOrderByInput = {
  /**
   * Rank
   */
  rank: "asc" | "desc";
};

/**
 * _Binding_playlistId_OrderByInput
 */
export type BindingsModelsBindingPlaylistIdOrderByInput = {
  /**
   * Playlistid
   */
  playlistId: "asc" | "desc";
};

/**
 * _Binding_mediaId_OrderByInput
 */
export type BindingsModelsBindingMediaIdOrderByInput = {
  /**
   * Mediaid
   */
  mediaId: "asc" | "desc";
};

/**
 * _Binding_id_OrderByInput
 */
export type BindingsModelsBindingIdOrderByInput = {
  /**
   * Id
   */
  id: "asc" | "desc";
};

/**
 * _Binding_RelevanceOrderByInput
 */
export type BindingsModelsBindingRelevanceOrderByInput = {
  _relevance: BindingsModelsBindingRelevanceInner;
};

/**
 * _Binding_RelevanceInner
 */
export type BindingsModelsBindingRelevanceInner = {
  /**
   * Fields
   */
  fields: Array<"id" | "playlistId" | "mediaId" | "rank">;
  /**
   * Search
   */
  search: string;
  /**
   * Sort
   */
  sort: "asc" | "desc";
};

/**
 * _BindingWhereUnique_id_Input
 */
export type BindingsModelsBindingWhereUniqueIdInput = {
  /**
   * Id
   */
  id: string;
};

/**
 * _BindingCompoundplaylistId_rankKeyInner
 */
export type BindingsModelsBindingCompoundplaylistIdRankKeyInner = {
  /**
   * Playlistid
   */
  playlistId: string;
  /**
   * Rank
   */
  rank: string;
};

/**
 * _BindingCompoundplaylistId_rankKey
 */
export type BindingsModelsBindingCompoundplaylistIdRankKey = {
  playlistidRank: BindingsModelsBindingCompoundplaylistIdRankKeyInner;
};

export type BindingsModelsUpdateRequestInclude = BindingInclude | null;

/**
 * FindManyBindingArgsFromMedia
 *
 * Arguments for Media
 */
export type BindingsModelsFindManyBindingArgsFromMedia = {
  /**
   * Take
   */
  take?: number;
  /**
   * Skip
   */
  skip?: number;
  /**
   * Orderby
   */
  orderBy?:
    | BindingsModelsBindingIdOrderByInput
    | BindingsModelsBindingPlaylistIdOrderByInput
    | BindingsModelsBindingMediaIdOrderByInput
    | BindingsModelsBindingRankOrderByInput
    | BindingsModelsBindingRelevanceOrderByInput
    | Array<
        | BindingsModelsBindingIdOrderByInput
        | BindingsModelsBindingPlaylistIdOrderByInput
        | BindingsModelsBindingMediaIdOrderByInput
        | BindingsModelsBindingRankOrderByInput
        | BindingsModelsBindingRelevanceOrderByInput
      >;
  where?: BindingsModelsBindingWhereInput;
  /**
   * Cursor
   */
  cursor?:
    | BindingsModelsBindingWhereUniqueIdInput
    | BindingsModelsBindingCompoundplaylistIdRankKey;
  /**
   * Distinct
   */
  distinct?: Array<"id" | "playlistId" | "mediaId" | "rank">;
  include?: BindingsModelsBindingIncludeFromBinding;
};

/**
 * BindingIncludeFromBinding
 *
 * Relational arguments for Binding
 */
export type BindingsModelsBindingIncludeFromBinding = {
  /**
   * Playlist
   */
  playlist?: boolean | BindingsModelsPlaylistArgsFromBinding;
  /**
   * Media
   */
  media?: boolean | BindingsModelsMediaArgsFromBinding;
};

/**
 * MediaWhereInput
 *
 * Media arguments for searching
 */
export type BindingsModelsMediaWhereInput = {
  /**
   * Id
   */
  id?: string | BindingsModelsStringFilter;
  /**
   * Name
   */
  name?: string | BindingsModelsStringFilter;
  bindings?: BindingsModelsBindingListRelationFilter;
  /**
   * And
   */
  and?: Array<BindingsModelsMediaWhereInput>;
  /**
   * Or
   */
  or?: Array<BindingsModelsMediaWhereInput>;
  /**
   * Not
   */
  not?: Array<BindingsModelsMediaWhereInput>;
};

/**
 * BindingWhereInput
 *
 * Binding arguments for searching
 */
export type BindingsModelsBindingWhereInput = {
  /**
   * Id
   */
  id?: string | BindingsModelsStringFilter;
  /**
   * Playlistid
   */
  playlistId?: string | BindingsModelsStringFilter;
  /**
   * Mediaid
   */
  mediaId?: string | BindingsModelsStringFilter;
  /**
   * Rank
   */
  rank?: string | BindingsModelsStringFilter;
  playlist?: BindingsModelsPlaylistRelationFilter;
  media?: BindingsModelsMediaRelationFilter;
  /**
   * And
   */
  and?: Array<BindingsModelsBindingWhereInput>;
  /**
   * Or
   */
  or?: Array<BindingsModelsBindingWhereInput>;
  /**
   * Not
   */
  not?: Array<BindingsModelsBindingWhereInput>;
};

/**
 * MediaRelationFilter
 */
export type BindingsModelsMediaRelationFilter = {
  is?: BindingsModelsMediaWhereInput;
  isNot?: BindingsModelsMediaWhereInput;
};

/**
 * BindingListRelationFilter
 */
export type BindingsModelsBindingListRelationFilter = {
  some?: BindingsModelsBindingWhereInput;
  none?: BindingsModelsBindingWhereInput;
  every?: BindingsModelsBindingWhereInput;
};

/**
 * StringFilter
 */
export type BindingsModelsStringFilter = {
  /**
   * Equals
   */
  equals?: string;
  /**
   * Notin
   */
  notIn?: Array<string>;
  /**
   * Lt
   */
  lt?: string;
  /**
   * Lte
   */
  lte?: string;
  /**
   * Gt
   */
  gt?: string;
  /**
   * Gte
   */
  gte?: string;
  /**
   * Contains
   */
  contains?: string;
  /**
   * Startswith
   */
  startswith?: string;
  /**
   * Endswith
   */
  endswith?: string;
  /**
   * In
   */
  in?: Array<string>;
  /**
   * Not
   */
  not?: string | BindingsModelsStringFilter;
  /**
   * Mode
   */
  mode?: "default" | "insensitive";
  /**
   * Search
   */
  search?: string;
};

/**
 * PlaylistWhereInput
 *
 * Playlist arguments for searching
 */
export type BindingsModelsPlaylistWhereInput = {
  /**
   * Id
   */
  id?: string | BindingsModelsStringFilter;
  /**
   * Name
   */
  name?: string | BindingsModelsStringFilter;
  bindings?: BindingsModelsBindingListRelationFilter;
  /**
   * And
   */
  and?: Array<BindingsModelsPlaylistWhereInput>;
  /**
   * Or
   */
  or?: Array<BindingsModelsPlaylistWhereInput>;
  /**
   * Not
   */
  not?: Array<BindingsModelsPlaylistWhereInput>;
};

/**
 * PlaylistRelationFilter
 */
export type BindingsModelsPlaylistRelationFilter = {
  is?: BindingsModelsPlaylistWhereInput;
  isNot?: BindingsModelsPlaylistWhereInput;
};

/**
 * MediaIncludeFromMedia
 *
 * Relational arguments for Media
 */
export type BindingsModelsMediaIncludeFromMedia = {
  /**
   * Bindings
   */
  bindings?: boolean | BindingsModelsFindManyBindingArgsFromMedia;
};

/**
 * MediaArgsFromBinding
 *
 * Arguments for Binding
 */
export type BindingsModelsMediaArgsFromBinding = {
  include?: BindingsModelsMediaIncludeFromMedia;
};

/**
 * PlaylistArgsFromBinding
 *
 * Arguments for Binding
 */
export type BindingsModelsPlaylistArgsFromBinding = {
  include?: BindingsModelsPlaylistIncludeFromPlaylist;
};

/**
 * FindManyBindingArgsFromPlaylist
 *
 * Arguments for Playlist
 */
export type BindingsModelsFindManyBindingArgsFromPlaylist = {
  /**
   * Take
   */
  take?: number;
  /**
   * Skip
   */
  skip?: number;
  /**
   * Orderby
   */
  orderBy?:
    | BindingsModelsBindingIdOrderByInput
    | BindingsModelsBindingPlaylistIdOrderByInput
    | BindingsModelsBindingMediaIdOrderByInput
    | BindingsModelsBindingRankOrderByInput
    | BindingsModelsBindingRelevanceOrderByInput
    | Array<
        | BindingsModelsBindingIdOrderByInput
        | BindingsModelsBindingPlaylistIdOrderByInput
        | BindingsModelsBindingMediaIdOrderByInput
        | BindingsModelsBindingRankOrderByInput
        | BindingsModelsBindingRelevanceOrderByInput
      >;
  where?: BindingsModelsBindingWhereInput;
  /**
   * Cursor
   */
  cursor?:
    | BindingsModelsBindingWhereUniqueIdInput
    | BindingsModelsBindingCompoundplaylistIdRankKey;
  /**
   * Distinct
   */
  distinct?: Array<"id" | "playlistId" | "mediaId" | "rank">;
  include?: BindingsModelsBindingIncludeFromBinding;
};

/**
 * PlaylistIncludeFromPlaylist
 *
 * Relational arguments for Playlist
 */
export type BindingsModelsPlaylistIncludeFromPlaylist = {
  /**
   * Bindings
   */
  bindings?: boolean | BindingsModelsFindManyBindingArgsFromPlaylist;
};

/**
 * BindingInclude
 *
 * Binding relational arguments
 */
export type BindingInclude = {
  /**
   * Playlist
   */
  playlist?: boolean | BindingsModelsPlaylistArgsFromBinding;
  /**
   * Media
   */
  media?: boolean | BindingsModelsMediaArgsFromBinding;
};

export type BindingsModelsUpdateRequestId = string;

/**
 * BindingUpdateManyMutationInput
 *
 * Arguments for updating many records
 */
export type BindingsModelsUpdateRequestData = {
  /**
   * Id
   */
  id?: string;
  /**
   * Rank
   */
  rank?: string;
};

/**
 * Playlist
 *
 * Playlist data.
 */
export type BindingsModelsPlaylist = {
  /**
   * Id
   *
   * Identifier of the playlist.
   */
  id: string;
  /**
   * Name
   *
   * Name of the playlist.
   */
  name: string;
  /**
   * Bindings
   *
   * Bindings that the playlist belongs to.
   */
  bindings: Array<BindingsModelsBinding> | null;
};

/**
 * Binding
 *
 * Binding data.
 */
export type BindingsModelsBinding = {
  /**
   * Id
   *
   * Identifier of the binding.
   */
  id: string;
  /**
   * Playlistid
   *
   * Identifier of the playlist that the binding belongs to.
   */
  playlistId: string;
  /**
   * Mediaid
   *
   * Identifier of the media that the binding belongs to.
   */
  mediaId: string;
  /**
   * Rank
   *
   * Rank of the media in the binding.
   */
  rank: string;
  /**
   * Playlist that the binding belongs to.
   */
  playlist: BindingsModelsPlaylist | null;
  /**
   * Media that the binding belongs to.
   */
  media: BindingsModelsMedia | null;
};

/**
 * Media
 *
 * Media data.
 */
export type BindingsModelsMedia = {
  /**
   * Id
   *
   * Identifier of the media.
   */
  id: string;
  /**
   * Name
   *
   * Name of the media.
   */
  name: string;
  /**
   * Bindings
   *
   * Bindings that the media belongs to.
   */
  bindings: Array<BindingsModelsBinding> | null;
};

/**
 * BindingList
 *
 * List of bindings.
 */
export type BindingsModelsListResponseResults = {
  /**
   * Count
   *
   * Total number of bindings that matched the query.
   */
  count: number;
  /**
   * Limit
   *
   * Maximum number of returned bindings.
   */
  limit: number | null;
  /**
   * Offset
   *
   * Number of bindings skipped.
   */
  offset: number | null;
  /**
   * Bindings
   *
   * Bindings that matched the request.
   */
  bindings: Array<BindingsModelsBinding>;
};

export type BindingsModelsListRequestWhere =
  BindingsModelsBindingWhereInput | null;

export type BindingsModelsListRequestOrder =
  | BindingOrderByInput
  | Array<BindingOrderByInput>
  | null;

export type BindingOrderByInput =
  | BindingsModelsBindingIdOrderByInput
  | BindingsModelsBindingPlaylistIdOrderByInput
  | BindingsModelsBindingMediaIdOrderByInput
  | BindingsModelsBindingRankOrderByInput;

export type BindingsModelsListRequestOffset = number | null;

export type BindingsModelsListRequestLimit = number | null;

export type BindingsModelsListRequestInclude = BindingInclude | null;

export type BindingsModelsGetRequestInclude = BindingInclude | null;

export type BindingsModelsGetRequestId = string;

export type BindingsModelsDeleteRequestId = string;

export type BindingsModelsCreateRequestInclude = BindingInclude | null;

/**
 * BindingCreateInput
 *
 * Required arguments to the Binding create method.
 */
export type BindingsModelsCreateRequestData = {
  /**
   * Id
   */
  id?: string;
  /**
   * Playlistid
   *
   * Identifier of the playlist.
   */
  playlistId: string;
  /**
   * Mediaid
   *
   * Identifier of the media.
   */
  mediaId: string;
  /**
   * Rank
   *
   * Rank of the binding.
   */
  rank: string;
};

export type UploadRequestType = string;

export type UploadRequestId = string;

/**
 * Result
 *
 * Result of the test.
 */
export type TestResponseResult = {
  /**
   * Success
   *
   * Indicates if the test was successful.
   */
  success: boolean;
  /**
   * Message
   *
   * Message returned from the test.
   */
  message: string;
};

export type TestRequestParameters = Parameters | null;

/**
 * Parameters
 *
 * Parameters for testing.
 */
export type Parameters = {
  /**
   * Message
   *
   * Optional message to include in the test.
   */
  message?: string | null;
};

export type SubscribeRequestTypes = string | Array<EventType> | null;

/**
 * EventType
 *
 * Event types.
 */
export type EventType =
  | "test"
  | "binding-created"
  | "binding-updated"
  | "binding-deleted"
  | "media-created"
  | "media-updated"
  | "media-deleted"
  | "playlist-created"
  | "playlist-updated"
  | "playlist-deleted";

export type M3uRequestId = string;

export type HeadM3uRequestId = string;

/**
 * Playlist
 *
 * Playlist data.
 */
export type GetResponsePlaylist = {
  /**
   * Id
   *
   * Identifier of the playlist.
   */
  id: string;
  /**
   * Name
   *
   * Name of the playlist.
   */
  name: string;
  /**
   * Bindings
   *
   * Bindings that the playlist belongs to.
   */
  bindings: Array<PlaylistsModelsBinding> | null;
};

/**
 * Media
 *
 * Media data.
 */
export type GetResponseMedia = {
  /**
   * Id
   *
   * Identifier of the media.
   */
  id: string;
  /**
   * Name
   *
   * Name of the media.
   */
  name: string;
  /**
   * Bindings
   *
   * Bindings that the media belongs to.
   */
  bindings: Array<MediaModelsBinding> | null;
};

/**
 * Binding
 *
 * Binding data.
 */
export type GetResponseBinding = {
  /**
   * Id
   *
   * Identifier of the binding.
   */
  id: string;
  /**
   * Playlistid
   *
   * Identifier of the playlist that the binding belongs to.
   */
  playlistId: string;
  /**
   * Mediaid
   *
   * Identifier of the media that the binding belongs to.
   */
  mediaId: string;
  /**
   * Rank
   *
   * Rank of the media in the binding.
   */
  rank: string;
  /**
   * Playlist that the binding belongs to.
   */
  playlist: BindingsModelsPlaylist | null;
  /**
   * Media that the binding belongs to.
   */
  media: BindingsModelsMedia | null;
};

export type DownloadRequestId = string;

export type BindingsListRequest = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Maximum number of bindings to return. Default is 10.
     */
    limit?: BindingsModelsListRequestLimit | string | null;
    /**
     * Number of bindings to skip.
     */
    offset?: BindingsModelsListRequestOffset | string | null;
    /**
     * Filter to apply to find bindings.
     */
    where?: BindingsModelsListRequestWhere | string | null;
    /**
     * Relations to include in the response.
     */
    include?: BindingsModelsListRequestInclude | string | null;
    /**
     * Order to apply to the results.
     */
    order?: BindingsModelsListRequestOrder | string | null;
  };
  url: "/bindings";
};

export type BindingsListErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type BindingsListError = BindingsListErrors[keyof BindingsListErrors];

export type BindingsListResponses = {
  /**
   * Request fulfilled, document follows
   */
  200: BindingsModelsListResponseResults;
};

export type BindingsListResponse =
  BindingsListResponses[keyof BindingsListResponses];

export type BindingsCreateRequest = {
  body: BindingsModelsCreateRequestData;
  path?: never;
  query?: {
    /**
     * Relations to include in the response.
     */
    include?: BindingsModelsCreateRequestInclude | string | null;
  };
  url: "/bindings";
};

export type BindingsCreateErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type BindingsCreateError =
  BindingsCreateErrors[keyof BindingsCreateErrors];

export type BindingsCreateResponses = {
  /**
   * Document created, URL follows
   */
  201: BindingsModelsBinding;
};

export type BindingsCreateResponse =
  BindingsCreateResponses[keyof BindingsCreateResponses];

export type BindingsIdDeleteRequest = {
  body?: never;
  path: {
    id: BindingsModelsDeleteRequestId;
  };
  query?: never;
  url: "/bindings/{id}";
};

export type BindingsIdDeleteErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
  /**
   * Not Found Exception
   */
  404: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type BindingsIdDeleteError =
  BindingsIdDeleteErrors[keyof BindingsIdDeleteErrors];

export type BindingsIdDeleteResponses = {
  /**
   * Request fulfilled, nothing follows
   */
  204: void;
};

export type BindingsIdDeleteResponse =
  BindingsIdDeleteResponses[keyof BindingsIdDeleteResponses];

export type BindingsIdGetRequest = {
  body?: never;
  path: {
    id: BindingsModelsGetRequestId;
  };
  query?: {
    /**
     * Relations to include in the response.
     */
    include?: BindingsModelsGetRequestInclude | string | null;
  };
  url: "/bindings/{id}";
};

export type BindingsIdGetErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
  /**
   * Not Found Exception
   */
  404: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type BindingsIdGetError = BindingsIdGetErrors[keyof BindingsIdGetErrors];

export type BindingsIdGetResponses = {
  /**
   * Request fulfilled, document follows
   */
  200: GetResponseBinding;
};

export type BindingsIdGetResponse =
  BindingsIdGetResponses[keyof BindingsIdGetResponses];

export type BindingsIdUpdateRequest = {
  body: BindingsModelsUpdateRequestData;
  path: {
    id: BindingsModelsUpdateRequestId;
  };
  query?: {
    /**
     * Relations to include in the response.
     */
    include?: BindingsModelsUpdateRequestInclude | string | null;
  };
  url: "/bindings/{id}";
};

export type BindingsIdUpdateErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
  /**
   * Not Found Exception
   */
  404: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type BindingsIdUpdateError =
  BindingsIdUpdateErrors[keyof BindingsIdUpdateErrors];

export type BindingsIdUpdateResponses = {
  /**
   * Request fulfilled, document follows
   */
  200: BindingsModelsBinding;
};

export type BindingsIdUpdateResponse =
  BindingsIdUpdateResponses[keyof BindingsIdUpdateResponses];

export type MediaListRequest = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Maximum number of media to return. Default is 10.
     */
    limit?: MediaModelsListRequestLimit | string | null;
    /**
     * Number of media to skip.
     */
    offset?: MediaModelsListRequestOffset | string | null;
    /**
     * Filter to apply to find media.
     */
    where?: MediaModelsListRequestWhere | string | null;
    /**
     * Relations to include in the response.
     */
    include?: MediaModelsListRequestInclude | string | null;
    /**
     * Order to apply to the results.
     */
    order?: MediaModelsListRequestOrder | string | null;
  };
  url: "/media";
};

export type MediaListErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type MediaListError = MediaListErrors[keyof MediaListErrors];

export type MediaListResponses = {
  /**
   * Request fulfilled, document follows
   */
  200: MediaModelsListResponseResults;
};

export type MediaListResponse = MediaListResponses[keyof MediaListResponses];

export type MediaCreateRequest = {
  body: MediaModelsCreateRequestData;
  path?: never;
  query?: {
    /**
     * Relations to include in the response.
     */
    include?: MediaModelsCreateRequestInclude | string | null;
  };
  url: "/media";
};

export type MediaCreateErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type MediaCreateError = MediaCreateErrors[keyof MediaCreateErrors];

export type MediaCreateResponses = {
  /**
   * Document created, URL follows
   */
  201: MediaModelsMedia;
};

export type MediaCreateResponse =
  MediaCreateResponses[keyof MediaCreateResponses];

export type MediaIdDeleteRequest = {
  body?: never;
  path: {
    id: MediaModelsDeleteRequestId;
  };
  query?: never;
  url: "/media/{id}";
};

export type MediaIdDeleteErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
  /**
   * Not Found Exception
   */
  404: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type MediaIdDeleteError = MediaIdDeleteErrors[keyof MediaIdDeleteErrors];

export type MediaIdDeleteResponses = {
  /**
   * Request fulfilled, nothing follows
   */
  204: void;
};

export type MediaIdDeleteResponse =
  MediaIdDeleteResponses[keyof MediaIdDeleteResponses];

export type MediaIdGetRequest = {
  body?: never;
  path: {
    id: MediaModelsGetRequestId;
  };
  query?: {
    /**
     * Relations to include in the response.
     */
    include?: MediaModelsGetRequestInclude | string | null;
  };
  url: "/media/{id}";
};

export type MediaIdGetErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
  /**
   * Not Found Exception
   */
  404: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type MediaIdGetError = MediaIdGetErrors[keyof MediaIdGetErrors];

export type MediaIdGetResponses = {
  /**
   * Request fulfilled, document follows
   */
  200: GetResponseMedia;
};

export type MediaIdGetResponse = MediaIdGetResponses[keyof MediaIdGetResponses];

export type MediaIdUpdateRequest = {
  body: MediaModelsUpdateRequestData;
  path: {
    id: MediaModelsUpdateRequestId;
  };
  query?: {
    /**
     * Relations to include in the response.
     */
    include?: MediaModelsUpdateRequestInclude | string | null;
  };
  url: "/media/{id}";
};

export type MediaIdUpdateErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
  /**
   * Not Found Exception
   */
  404: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type MediaIdUpdateError = MediaIdUpdateErrors[keyof MediaIdUpdateErrors];

export type MediaIdUpdateResponses = {
  /**
   * Request fulfilled, document follows
   */
  200: MediaModelsMedia;
};

export type MediaIdUpdateResponse =
  MediaIdUpdateResponses[keyof MediaIdUpdateResponses];

export type MediaIdContentDownloadRequest = {
  body?: never;
  path: {
    id: DownloadRequestId;
  };
  query?: never;
  url: "/media/{id}/content";
};

export type MediaIdContentDownloadErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
  /**
   * Not Found Exception
   */
  404: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type MediaIdContentDownloadError =
  MediaIdContentDownloadErrors[keyof MediaIdContentDownloadErrors];

export type MediaIdContentDownloadResponses = {
  /**
   * Stream Response
   */
  200: ReadableStream;
};

export type MediaIdContentDownloadResponse =
  MediaIdContentDownloadResponses[keyof MediaIdContentDownloadResponses];

export type MediaIdContentHeaddownloadRequest = {
  body?: never;
  path: {
    id: DownloadRequestId;
  };
  query?: never;
  url: "/media/{id}/content";
};

export type MediaIdContentHeaddownloadErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
  /**
   * Not Found Exception
   */
  404: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type MediaIdContentHeaddownloadError =
  MediaIdContentHeaddownloadErrors[keyof MediaIdContentHeaddownloadErrors];

export type MediaIdContentHeaddownloadResponses = {
  /**
   * Request fulfilled, headers follow
   */
  200: unknown;
};

export type MediaIdContentUploadRequest = {
  body: ReadableStream;
  headers: {
    /**
     * UploadRequestType
     *
     * Content type.
     */
    "Content-Type": UploadRequestType | string;
  };
  path: {
    id: UploadRequestId;
  };
  query?: never;
  url: "/media/{id}/content";
};

export type MediaIdContentUploadErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
  /**
   * Not Found Exception
   */
  404: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type MediaIdContentUploadError =
  MediaIdContentUploadErrors[keyof MediaIdContentUploadErrors];

export type MediaIdContentUploadResponses = {
  /**
   * Request fulfilled, nothing follows
   */
  204: void;
};

export type MediaIdContentUploadResponse =
  MediaIdContentUploadResponses[keyof MediaIdContentUploadResponses];

export type PingPingRequest = {
  body?: never;
  path?: never;
  query?: never;
  url: "/ping";
};

export type PingPingResponses = {
  /**
   * Request fulfilled, nothing follows
   */
  204: void;
};

export type PingPingResponse = PingPingResponses[keyof PingPingResponses];

export type PingHeadpingRequest = {
  body?: never;
  path?: never;
  query?: never;
  url: "/ping";
};

export type PingHeadpingResponses = {
  /**
   * Request fulfilled, nothing follows
   */
  204: void;
};

export type PingHeadpingResponse =
  PingHeadpingResponses[keyof PingHeadpingResponses];

export type PlaylistsListRequest = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Maximum number of playlists to return. Default is 10.
     */
    limit?: PlaylistsModelsListRequestLimit | string | null;
    /**
     * Number of playlists to skip.
     */
    offset?: PlaylistsModelsListRequestOffset | string | null;
    /**
     * Filter to apply to find playlists.
     */
    where?: PlaylistsModelsListRequestWhere | string | null;
    /**
     * Relations to include in the response.
     */
    include?: PlaylistsModelsListRequestInclude | string | null;
    /**
     * Order to apply to the results.
     */
    order?: PlaylistsModelsListRequestOrder | string | null;
  };
  url: "/playlists";
};

export type PlaylistsListErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type PlaylistsListError = PlaylistsListErrors[keyof PlaylistsListErrors];

export type PlaylistsListResponses = {
  /**
   * Request fulfilled, document follows
   */
  200: PlaylistsModelsListResponseResults;
};

export type PlaylistsListResponse =
  PlaylistsListResponses[keyof PlaylistsListResponses];

export type PlaylistsCreateRequest = {
  body: PlaylistsModelsCreateRequestData;
  path?: never;
  query?: {
    /**
     * Relations to include in the response.
     */
    include?: PlaylistsModelsCreateRequestInclude | string | null;
  };
  url: "/playlists";
};

export type PlaylistsCreateErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type PlaylistsCreateError =
  PlaylistsCreateErrors[keyof PlaylistsCreateErrors];

export type PlaylistsCreateResponses = {
  /**
   * Document created, URL follows
   */
  201: PlaylistsModelsPlaylist;
};

export type PlaylistsCreateResponse =
  PlaylistsCreateResponses[keyof PlaylistsCreateResponses];

export type PlaylistsIdDeleteRequest = {
  body?: never;
  path: {
    id: PlaylistsModelsDeleteRequestId;
  };
  query?: never;
  url: "/playlists/{id}";
};

export type PlaylistsIdDeleteErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
  /**
   * Not Found Exception
   */
  404: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type PlaylistsIdDeleteError =
  PlaylistsIdDeleteErrors[keyof PlaylistsIdDeleteErrors];

export type PlaylistsIdDeleteResponses = {
  /**
   * Request fulfilled, nothing follows
   */
  204: void;
};

export type PlaylistsIdDeleteResponse =
  PlaylistsIdDeleteResponses[keyof PlaylistsIdDeleteResponses];

export type PlaylistsIdGetRequest = {
  body?: never;
  path: {
    id: PlaylistsModelsGetRequestId;
  };
  query?: {
    /**
     * Relations to include in the response.
     */
    include?: PlaylistsModelsGetRequestInclude | string | null;
  };
  url: "/playlists/{id}";
};

export type PlaylistsIdGetErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
  /**
   * Not Found Exception
   */
  404: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type PlaylistsIdGetError =
  PlaylistsIdGetErrors[keyof PlaylistsIdGetErrors];

export type PlaylistsIdGetResponses = {
  /**
   * Request fulfilled, document follows
   */
  200: GetResponsePlaylist;
};

export type PlaylistsIdGetResponse =
  PlaylistsIdGetResponses[keyof PlaylistsIdGetResponses];

export type PlaylistsIdUpdateRequest = {
  body: PlaylistsModelsUpdateRequestData;
  path: {
    id: PlaylistsModelsUpdateRequestId;
  };
  query?: {
    /**
     * Relations to include in the response.
     */
    include?: PlaylistsModelsUpdateRequestInclude | string | null;
  };
  url: "/playlists/{id}";
};

export type PlaylistsIdUpdateErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
  /**
   * Not Found Exception
   */
  404: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type PlaylistsIdUpdateError =
  PlaylistsIdUpdateErrors[keyof PlaylistsIdUpdateErrors];

export type PlaylistsIdUpdateResponses = {
  /**
   * Request fulfilled, document follows
   */
  200: PlaylistsModelsPlaylist;
};

export type PlaylistsIdUpdateResponse =
  PlaylistsIdUpdateResponses[keyof PlaylistsIdUpdateResponses];

export type PlaylistsIdM3Um3uRequest = {
  body?: never;
  path: {
    id: M3uRequestId;
  };
  query?: never;
  url: "/playlists/{id}/m3u";
};

export type PlaylistsIdM3Um3uErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
  /**
   * Not Found Exception
   */
  404: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type PlaylistsIdM3Um3uError =
  PlaylistsIdM3Um3uErrors[keyof PlaylistsIdM3Um3uErrors];

export type PlaylistsIdM3Um3uResponses = {
  /**
   * Request fulfilled, document follows
   */
  200: string;
};

export type PlaylistsIdM3Um3uResponse =
  PlaylistsIdM3Um3uResponses[keyof PlaylistsIdM3Um3uResponses];

export type PlaylistsIdM3uHeadm3uRequest = {
  body?: never;
  path: {
    id: HeadM3uRequestId;
  };
  query?: never;
  url: "/playlists/{id}/m3u";
};

export type PlaylistsIdM3uHeadm3uErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
  /**
   * Not Found Exception
   */
  404: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type PlaylistsIdM3uHeadm3uError =
  PlaylistsIdM3uHeadm3uErrors[keyof PlaylistsIdM3uHeadm3uErrors];

export type PlaylistsIdM3uHeadm3uResponses = {
  /**
   * Request fulfilled, headers follow
   */
  200: unknown;
};

export type SseSubscribeRequest = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Types of events to subscribe to.
     */
    types?: SubscribeRequestTypes | string | null;
  };
  url: "/sse";
};

export type SseSubscribeErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type SseSubscribeError = SseSubscribeErrors[keyof SseSubscribeErrors];

export type SseSubscribeResponses = {
  /**
   * Request fulfilled, stream of Server-Sent Events follows
   */
  200: string;
};

export type SseSubscribeResponse =
  SseSubscribeResponses[keyof SseSubscribeResponses];

export type TestTestRequest = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Parameters for testing.
     */
    parameters?: TestRequestParameters | string | null;
  };
  url: "/test";
};

export type TestTestErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type TestTestError = TestTestErrors[keyof TestTestErrors];

export type TestTestResponses = {
  /**
   * Request fulfilled, document follows
   */
  200: TestResponseResult;
};

export type TestTestResponse = TestTestResponses[keyof TestTestResponses];
