/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = {
  "/bindings": {
    delete?: never;
    /**
     * List bindings
     * @description List bindings that match the request.
     */
    get: operations["BindingsList"];
    head?: never;
    options?: never;
    parameters: {
      cookie?: never;
      header?: never;
      path?: never;
      query?: never;
    };
    patch?: never;
    /**
     * Create binding
     * @description Create a new binding.
     */
    post: operations["BindingsCreate"];
    put?: never;
    trace?: never;
  };
  "/bindings/{id}": {
    /**
     * Delete binding
     * @description Delete a binding by ID.
     */
    delete: operations["BindingsIdDelete"];
    /**
     * Get binding
     * @description Get a binding by ID.
     */
    get: operations["BindingsIdGet"];
    head?: never;
    options?: never;
    parameters: {
      cookie?: never;
      header?: never;
      path?: never;
      query?: never;
    };
    /**
     * Update binding
     * @description Update a binding by ID.
     */
    patch: operations["BindingsIdUpdate"];
    post?: never;
    put?: never;
    trace?: never;
  };
  "/media": {
    delete?: never;
    /**
     * List media
     * @description List media that match the request.
     */
    get: operations["MediaList"];
    head?: never;
    options?: never;
    parameters: {
      cookie?: never;
      header?: never;
      path?: never;
      query?: never;
    };
    patch?: never;
    /**
     * Create media
     * @description Create new media.
     */
    post: operations["MediaCreate"];
    put?: never;
    trace?: never;
  };
  "/media/{id}": {
    /**
     * Delete media
     * @description Delete media by ID.
     */
    delete: operations["MediaIdDelete"];
    /**
     * Get media
     * @description Get media by ID.
     */
    get: operations["MediaIdGet"];
    head?: never;
    options?: never;
    parameters: {
      cookie?: never;
      header?: never;
      path?: never;
      query?: never;
    };
    /**
     * Update media
     * @description Update media by ID.
     */
    patch: operations["MediaIdUpdate"];
    post?: never;
    put?: never;
    trace?: never;
  };
  "/media/{id}/content": {
    delete?: never;
    /**
     * Download media content
     * @description Download media content by ID.
     */
    get: operations["MediaIdContentDownload"];
    /**
     * Get media content headers
     * @description Get media content headers by ID.
     */
    head: operations["MediaIdContentHeaddownload"];
    options?: never;
    parameters: {
      cookie?: never;
      header?: never;
      path?: never;
      query?: never;
    };
    patch?: never;
    post?: never;
    /**
     * Upload media content
     * @description Upload media content by ID.
     */
    put: operations["MediaIdContentUpload"];
    trace?: never;
  };
  "/ping": {
    delete?: never;
    /**
     * Ping
     * @description Ping.
     */
    get: operations["PingPing"];
    /**
     * Ping headers
     * @description Ping headers.
     */
    head: operations["PingHeadping"];
    options?: never;
    parameters: {
      cookie?: never;
      header?: never;
      path?: never;
      query?: never;
    };
    patch?: never;
    post?: never;
    put?: never;
    trace?: never;
  };
  "/playlists": {
    delete?: never;
    /**
     * List playlists
     * @description List playlists that match the request.
     */
    get: operations["PlaylistsList"];
    head?: never;
    options?: never;
    parameters: {
      cookie?: never;
      header?: never;
      path?: never;
      query?: never;
    };
    patch?: never;
    /**
     * Create playlist
     * @description Create a new playlist.
     */
    post: operations["PlaylistsCreate"];
    put?: never;
    trace?: never;
  };
  "/playlists/{id}": {
    /**
     * Delete playlist
     * @description Delete a playlist by ID.
     */
    delete: operations["PlaylistsIdDelete"];
    /**
     * Get playlist
     * @description Get a playlist by ID.
     */
    get: operations["PlaylistsIdGet"];
    head?: never;
    options?: never;
    parameters: {
      cookie?: never;
      header?: never;
      path?: never;
      query?: never;
    };
    /**
     * Update playlist
     * @description Update a playlist by ID.
     */
    patch: operations["PlaylistsIdUpdate"];
    post?: never;
    put?: never;
    trace?: never;
  };
  "/playlists/{id}/m3u": {
    delete?: never;
    /**
     * Get playlist in M3U format
     * @description Get a playlist in M3U format.
     */
    get: operations["PlaylistsIdM3UM3U"];
    /**
     * Get headers for playlist in M3U format
     * @description Get headers for a playlist in M3U format.
     */
    head: operations["PlaylistsIdM3UHeadm3U"];
    options?: never;
    parameters: {
      cookie?: never;
      header?: never;
      path?: never;
      query?: never;
    };
    patch?: never;
    post?: never;
    put?: never;
    trace?: never;
  };
  "/sse": {
    delete?: never;
    /**
     * Get SSE stream
     * @description Get a stream of Server-Sent Events.
     */
    get: operations["SseSubscribe"];
    head?: never;
    options?: never;
    parameters: {
      cookie?: never;
      header?: never;
      path?: never;
      query?: never;
    };
    patch?: never;
    post?: never;
    put?: never;
    trace?: never;
  };
};
export type webhooks = { [key: string]: never };
export type components = {
  headers: never;
  parameters: never;
  pathItems: never;
  requestBodies: never;
  responses: never;
  schemas: {
    /**
     * BindingCreateInput
     * @description Data to create a binding.
     */
    BindingCreateInput: {
      id?: string;
      mediaId: string;
      playlistId: string;
      rank: string;
    };
    /** BindingList */
    BindingList: {
      /** @description Bindings that matched the request. */
      bindings: components["schemas"]["bindings_models_Binding"][];
      /** @description Total number of bindings that matched the query. */
      count: number;
      /** @description Maximum number of returned bindings. */
      limit?: null | number;
      /** @description Number of bindings skipped. */
      offset?: null | number;
    };
    /** Binding */
    bindings_models_Binding: {
      /**
       * Format: uuid
       * @description Identifier of the binding.
       */
      id: string;
      /** @description Media that the binding belongs to. */
      media?: components["schemas"]["bindings_models_Media"] | null;
      /**
       * Format: uuid
       * @description Identifier of the media that the binding belongs to.
       */
      mediaId: string;
      /** @description Playlist that the binding belongs to. */
      playlist?: components["schemas"]["bindings_models_Playlist"] | null;
      /**
       * Format: uuid
       * @description Identifier of the playlist that the binding belongs to.
       */
      playlistId: string;
      /** @description Rank of the media in the binding. */
      rank: string;
    };
    /** Media */
    bindings_models_Media: {
      /** @description Bindings that the media belongs to. */
      bindings?: components["schemas"]["bindings_models_Binding"][] | null;
      /**
       * Format: uuid
       * @description Identifier of the media.
       */
      id: string;
      /** @description Name of the media. */
      name: string;
    };
    /** Playlist */
    bindings_models_Playlist: {
      /** @description Bindings that the playlist belongs to. */
      bindings?: components["schemas"]["bindings_models_Binding"][] | null;
      /**
       * Format: uuid
       * @description Identifier of the playlist.
       */
      id: string;
      /** @description Name of the playlist. */
      name: string;
    };
    /**
     * BindingUpdateInput
     * @description Data to update a binding.
     */
    BindingUpdateInput: {
      id?: string;
      rank?: string;
    };
    /** Binding */
    media_models_Binding: {
      /**
       * Format: uuid
       * @description Identifier of the binding.
       */
      id: string;
      /** @description Media that the binding belongs to. */
      media?: components["schemas"]["media_models_Media"] | null;
      /**
       * Format: uuid
       * @description Identifier of the media that the binding belongs to.
       */
      mediaId: string;
      /** @description Playlist that the binding belongs to. */
      playlist?: components["schemas"]["media_models_Playlist"] | null;
      /**
       * Format: uuid
       * @description Identifier of the playlist that the binding belongs to.
       */
      playlistId: string;
      /** @description Rank of the media in the binding. */
      rank: string;
    };
    /** Media */
    media_models_Media: {
      /** @description Bindings that the media belongs to. */
      bindings?: components["schemas"]["media_models_Binding"][] | null;
      /**
       * Format: uuid
       * @description Identifier of the media.
       */
      id: string;
      /** @description Name of the media. */
      name: string;
    };
    /** Playlist */
    media_models_Playlist: {
      /** @description Bindings that the playlist belongs to. */
      bindings?: components["schemas"]["media_models_Binding"][] | null;
      /**
       * Format: uuid
       * @description Identifier of the playlist.
       */
      id: string;
      /** @description Name of the playlist. */
      name: string;
    };
    /**
     * MediaCreateInput
     * @description Data to create media.
     */
    MediaCreateInput: {
      id?: string;
      name: string;
    };
    /** MediaList */
    MediaList: {
      /** @description Total number of media that matched the query. */
      count: number;
      /** @description Maximum number of returned media. */
      limit?: null | number;
      /** @description Media that matched the request. */
      media: components["schemas"]["media_models_Media"][];
      /** @description Number of media skipped. */
      offset?: null | number;
    };
    /**
     * MediaUpdateInput
     * @description Data to update media.
     */
    MediaUpdateInput: {
      id?: string;
      name?: string;
    };
    /**
     * PlaylistCreateInput
     * @description Data to create a playlist.
     */
    PlaylistCreateInput: {
      id?: string;
      name: string;
    };
    /** PlaylistList */
    PlaylistList: {
      /** @description Total number of playlists that matched the query. */
      count: number;
      /** @description Maximum number of returned playlists. */
      limit?: null | number;
      /** @description Number of playlists skipped. */
      offset?: null | number;
      /** @description Playlists that matched the request. */
      playlists: components["schemas"]["playlists_models_Playlist"][];
    };
    /** Binding */
    playlists_models_Binding: {
      /**
       * Format: uuid
       * @description Identifier of the binding.
       */
      id: string;
      /** @description Media that the binding belongs to. */
      media?: components["schemas"]["playlists_models_Media"] | null;
      /**
       * Format: uuid
       * @description Identifier of the media that the binding belongs to.
       */
      mediaId: string;
      /** @description Playlist that the binding belongs to. */
      playlist?: components["schemas"]["playlists_models_Playlist"] | null;
      /**
       * Format: uuid
       * @description Identifier of the playlist that the binding belongs to.
       */
      playlistId: string;
      /** @description Rank of the media in the binding. */
      rank: string;
    };
    /** Media */
    playlists_models_Media: {
      /** @description Bindings that the media belongs to. */
      bindings?: components["schemas"]["playlists_models_Binding"][] | null;
      /**
       * Format: uuid
       * @description Identifier of the media.
       */
      id: string;
      /** @description Name of the media. */
      name: string;
    };
    /** Playlist */
    playlists_models_Playlist: {
      /** @description Bindings that the playlist belongs to. */
      bindings?: components["schemas"]["playlists_models_Binding"][] | null;
      /**
       * Format: uuid
       * @description Identifier of the playlist.
       */
      id: string;
      /** @description Name of the playlist. */
      name: string;
    };
    /**
     * PlaylistUpdateInput
     * @description Data to update a playlist.
     */
    PlaylistUpdateInput: {
      id?: string;
      name?: string;
    };
  };
};
export type $defs = { [key: string]: never };
export type operations = {
  BindingsCreate: {
    parameters: {
      cookie?: never;
      header?: never;
      path?: never;
      query?: {
        /** @description Relations to include in the response. */
        include?: null | string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BindingCreateInput"];
      };
    };
    responses: {
      /** @description Document created, URL follows */
      201: {
        content: {
          "application/json": components["schemas"]["bindings_models_Binding"];
        };
        headers: {
          [name: string]: unknown;
        };
      };
      /** @description Bad request syntax or unsupported method */
      400: {
        content: {
          "application/json": {
            detail: string;
            extra?:
              | {
                  [key: string]: unknown;
                }
              | null
              | unknown[];
            status_code: number;
          };
        };
        headers: {
          [name: string]: unknown;
        };
      };
    };
  };
  BindingsIdDelete: {
    parameters: {
      cookie?: never;
      header?: never;
      path: {
        /** @description Identifier of the binding to delete. */
        id: string;
      };
      query?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Request fulfilled, nothing follows */
      204: {
        content: {
          "application/json": null;
        };
        headers: {
          [name: string]: unknown;
        };
      };
      /** @description Bad request syntax or unsupported method */
      400: {
        content: {
          "application/json": {
            detail: string;
            extra?:
              | {
                  [key: string]: unknown;
                }
              | null
              | unknown[];
            status_code: number;
          };
        };
        headers: {
          [name: string]: unknown;
        };
      };
    };
  };
  BindingsIdGet: {
    parameters: {
      cookie?: never;
      header?: never;
      path: {
        /** @description Identifier of the binding to get. */
        id: string;
      };
      query?: {
        /** @description Relations to include in the response. */
        include?: null | string;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Request fulfilled, document follows */
      200: {
        content: {
          "application/json": components["schemas"]["bindings_models_Binding"];
        };
        headers: {
          [name: string]: unknown;
        };
      };
      /** @description Bad request syntax or unsupported method */
      400: {
        content: {
          "application/json": {
            detail: string;
            extra?:
              | {
                  [key: string]: unknown;
                }
              | null
              | unknown[];
            status_code: number;
          };
        };
        headers: {
          [name: string]: unknown;
        };
      };
    };
  };
  BindingsIdUpdate: {
    parameters: {
      cookie?: never;
      header?: never;
      path: {
        /** @description Identifier of the binding to update. */
        id: string;
      };
      query?: {
        /** @description Relations to include in the response. */
        include?: null | string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BindingUpdateInput"];
      };
    };
    responses: {
      /** @description Request fulfilled, document follows */
      200: {
        content: {
          "application/json": components["schemas"]["bindings_models_Binding"];
        };
        headers: {
          [name: string]: unknown;
        };
      };
      /** @description Bad request syntax or unsupported method */
      400: {
        content: {
          "application/json": {
            detail: string;
            extra?:
              | {
                  [key: string]: unknown;
                }
              | null
              | unknown[];
            status_code: number;
          };
        };
        headers: {
          [name: string]: unknown;
        };
      };
    };
  };
  BindingsList: {
    parameters: {
      cookie?: never;
      header?: never;
      path?: never;
      query?: {
        /** @description Relations to include in the response. */
        include?: null | string;
        /** @description Maximum number of bindings to return. */
        limit?: null | number;
        /** @description Number of bindings to skip. */
        offset?: null | number;
        /** @description Order to apply to the results. */
        order?: null | string;
        /** @description Filter to apply to find bindings. */
        where?: null | string;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Request fulfilled, document follows */
      200: {
        content: {
          "application/json": components["schemas"]["BindingList"];
        };
        headers: {
          [name: string]: unknown;
        };
      };
      /** @description Bad request syntax or unsupported method */
      400: {
        content: {
          "application/json": {
            detail: string;
            extra?:
              | {
                  [key: string]: unknown;
                }
              | null
              | unknown[];
            status_code: number;
          };
        };
        headers: {
          [name: string]: unknown;
        };
      };
    };
  };
  MediaCreate: {
    parameters: {
      cookie?: never;
      header?: never;
      path?: never;
      query?: {
        /** @description Relations to include in the response. */
        include?: null | string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MediaCreateInput"];
      };
    };
    responses: {
      /** @description Document created, URL follows */
      201: {
        content: {
          "application/json": components["schemas"]["media_models_Media"];
        };
        headers: {
          [name: string]: unknown;
        };
      };
      /** @description Bad request syntax or unsupported method */
      400: {
        content: {
          "application/json": {
            detail: string;
            extra?:
              | {
                  [key: string]: unknown;
                }
              | null
              | unknown[];
            status_code: number;
          };
        };
        headers: {
          [name: string]: unknown;
        };
      };
    };
  };
  MediaIdContentDownload: {
    parameters: {
      cookie?: never;
      header?: never;
      path: {
        /** @description Identifier of the media to download content for. */
        id: string;
      };
      query?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Stream Response */
      200: {
        content: {
          "": string;
        };
        headers: {
          [name: string]: unknown;
          /** @description File size in bytes */
          "content-length"?: string;
          /** @description Content length. */
          "Content-Length"?: unknown;
          /** @description Content type. */
          "Content-Type"?: unknown;
          /** @description Entity tag */
          etag?: string;
          /** @description Entity tag. */
          ETag?: unknown;
          /** @description Last modified data-time in RFC 2822 format */
          "last-modified"?: string;
          /** @description Last modified. */
          "Last-Modified"?: unknown;
        };
      };
      /** @description Bad request syntax or unsupported method */
      400: {
        content: {
          "application/json": {
            detail: string;
            extra?:
              | {
                  [key: string]: unknown;
                }
              | null
              | unknown[];
            status_code: number;
          };
        };
        headers: {
          [name: string]: unknown;
        };
      };
    };
  };
  MediaIdContentHeaddownload: {
    parameters: {
      cookie?: never;
      header?: never;
      path: {
        /** @description Identifier of the media to get content headers for. */
        id: string;
      };
      query?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Request fulfilled, document follows */
      200: {
        content: {
          "application/json": null;
        };
        headers: {
          [name: string]: unknown;
          /** @description Content length. */
          "Content-Length"?: unknown;
          /** @description Content type. */
          "Content-Type"?: unknown;
          /** @description Entity tag. */
          ETag?: unknown;
          /** @description Last modified. */
          "Last-Modified"?: unknown;
        };
      };
      /** @description Bad request syntax or unsupported method */
      400: {
        content: {
          "application/json": {
            detail: string;
            extra?:
              | {
                  [key: string]: unknown;
                }
              | null
              | unknown[];
            status_code: number;
          };
        };
        headers: {
          [name: string]: unknown;
        };
      };
    };
  };
  MediaIdContentUpload: {
    parameters: {
      cookie?: never;
      header: {
        /** @description Content type. */
        "Content-Type": string;
      };
      path: {
        /** @description Identifier of the media to upload content for. */
        id: string;
      };
      query?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Request fulfilled, nothing follows */
      204: {
        content: {
          "application/json": null;
        };
        headers: {
          [name: string]: unknown;
        };
      };
      /** @description Bad request syntax or unsupported method */
      400: {
        content: {
          "application/json": {
            detail: string;
            extra?:
              | {
                  [key: string]: unknown;
                }
              | null
              | unknown[];
            status_code: number;
          };
        };
        headers: {
          [name: string]: unknown;
        };
      };
    };
  };
  MediaIdDelete: {
    parameters: {
      cookie?: never;
      header?: never;
      path: {
        /** @description Identifier of the media to delete. */
        id: string;
      };
      query?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Request fulfilled, nothing follows */
      204: {
        content: {
          "application/json": null;
        };
        headers: {
          [name: string]: unknown;
        };
      };
      /** @description Bad request syntax or unsupported method */
      400: {
        content: {
          "application/json": {
            detail: string;
            extra?:
              | {
                  [key: string]: unknown;
                }
              | null
              | unknown[];
            status_code: number;
          };
        };
        headers: {
          [name: string]: unknown;
        };
      };
    };
  };
  MediaIdGet: {
    parameters: {
      cookie?: never;
      header?: never;
      path: {
        /** @description Identifier of the media to get. */
        id: string;
      };
      query?: {
        /** @description Relations to include in the response. */
        include?: null | string;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Request fulfilled, document follows */
      200: {
        content: {
          "application/json": components["schemas"]["media_models_Media"];
        };
        headers: {
          [name: string]: unknown;
        };
      };
      /** @description Bad request syntax or unsupported method */
      400: {
        content: {
          "application/json": {
            detail: string;
            extra?:
              | {
                  [key: string]: unknown;
                }
              | null
              | unknown[];
            status_code: number;
          };
        };
        headers: {
          [name: string]: unknown;
        };
      };
    };
  };
  MediaIdUpdate: {
    parameters: {
      cookie?: never;
      header?: never;
      path: {
        /** @description Identifier of the media to update. */
        id: string;
      };
      query?: {
        /** @description Relations to include in the response. */
        include?: null | string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MediaUpdateInput"];
      };
    };
    responses: {
      /** @description Request fulfilled, document follows */
      200: {
        content: {
          "application/json": components["schemas"]["media_models_Media"];
        };
        headers: {
          [name: string]: unknown;
        };
      };
      /** @description Bad request syntax or unsupported method */
      400: {
        content: {
          "application/json": {
            detail: string;
            extra?:
              | {
                  [key: string]: unknown;
                }
              | null
              | unknown[];
            status_code: number;
          };
        };
        headers: {
          [name: string]: unknown;
        };
      };
    };
  };
  MediaList: {
    parameters: {
      cookie?: never;
      header?: never;
      path?: never;
      query?: {
        /** @description Relations to include in the response. */
        include?: null | string;
        /** @description Maximum number of media to return. */
        limit?: null | number;
        /** @description Number of media to skip. */
        offset?: null | number;
        /** @description Order to apply to the results. */
        order?: null | string;
        /** @description Filter to apply to find media. */
        where?: null | string;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Request fulfilled, document follows */
      200: {
        content: {
          "application/json": components["schemas"]["MediaList"];
        };
        headers: {
          [name: string]: unknown;
        };
      };
      /** @description Bad request syntax or unsupported method */
      400: {
        content: {
          "application/json": {
            detail: string;
            extra?:
              | {
                  [key: string]: unknown;
                }
              | null
              | unknown[];
            status_code: number;
          };
        };
        headers: {
          [name: string]: unknown;
        };
      };
    };
  };
  PingHeadping: {
    parameters: {
      cookie?: never;
      header?: never;
      path?: never;
      query?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Request fulfilled, nothing follows */
      204: {
        content: {
          "application/json": null;
        };
        headers: {
          [name: string]: unknown;
          "cache-control"?: string;
        };
      };
    };
  };
  PingPing: {
    parameters: {
      cookie?: never;
      header?: never;
      path?: never;
      query?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Request fulfilled, nothing follows */
      204: {
        content: {
          "application/json": null;
        };
        headers: {
          [name: string]: unknown;
          "cache-control"?: string;
        };
      };
    };
  };
  PlaylistsCreate: {
    parameters: {
      cookie?: never;
      header?: never;
      path?: never;
      query?: {
        /** @description Relations to include in the response. */
        include?: null | string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PlaylistCreateInput"];
      };
    };
    responses: {
      /** @description Document created, URL follows */
      201: {
        content: {
          "application/json": components["schemas"]["playlists_models_Playlist"];
        };
        headers: {
          [name: string]: unknown;
        };
      };
      /** @description Bad request syntax or unsupported method */
      400: {
        content: {
          "application/json": {
            detail: string;
            extra?:
              | {
                  [key: string]: unknown;
                }
              | null
              | unknown[];
            status_code: number;
          };
        };
        headers: {
          [name: string]: unknown;
        };
      };
    };
  };
  PlaylistsIdDelete: {
    parameters: {
      cookie?: never;
      header?: never;
      path: {
        /** @description Identifier of the playlist to delete. */
        id: string;
      };
      query?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Request fulfilled, nothing follows */
      204: {
        content: {
          "application/json": null;
        };
        headers: {
          [name: string]: unknown;
        };
      };
      /** @description Bad request syntax or unsupported method */
      400: {
        content: {
          "application/json": {
            detail: string;
            extra?:
              | {
                  [key: string]: unknown;
                }
              | null
              | unknown[];
            status_code: number;
          };
        };
        headers: {
          [name: string]: unknown;
        };
      };
    };
  };
  PlaylistsIdGet: {
    parameters: {
      cookie?: never;
      header?: never;
      path: {
        /** @description Identifier of the playlist to get. */
        id: string;
      };
      query?: {
        /** @description Relations to include in the response. */
        include?: null | string;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Request fulfilled, document follows */
      200: {
        content: {
          "application/json": components["schemas"]["playlists_models_Playlist"];
        };
        headers: {
          [name: string]: unknown;
        };
      };
      /** @description Bad request syntax or unsupported method */
      400: {
        content: {
          "application/json": {
            detail: string;
            extra?:
              | {
                  [key: string]: unknown;
                }
              | null
              | unknown[];
            status_code: number;
          };
        };
        headers: {
          [name: string]: unknown;
        };
      };
    };
  };
  PlaylistsIdM3UHeadm3U: {
    parameters: {
      cookie?: never;
      header?: never;
      path: {
        /** @description Identifier of the playlist to get. */
        id: string;
      };
      query?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Request fulfilled, document follows */
      200: {
        content: {
          "application/json": null;
        };
        headers: {
          [name: string]: unknown;
          /** @description Content type. */
          "Content-Type"?: string;
        };
      };
      /** @description Bad request syntax or unsupported method */
      400: {
        content: {
          "application/json": {
            detail: string;
            extra?:
              | {
                  [key: string]: unknown;
                }
              | null
              | unknown[];
            status_code: number;
          };
        };
        headers: {
          [name: string]: unknown;
        };
      };
    };
  };
  PlaylistsIdM3UM3U: {
    parameters: {
      cookie?: never;
      header?: never;
      path: {
        /** @description Identifier of the playlist to get. */
        id: string;
      };
      query?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Request fulfilled, document follows */
      200: {
        content: {
          "audio/mpegurl": string;
        };
        headers: {
          [name: string]: unknown;
          /** @description Content type. */
          "Content-Type"?: string;
        };
      };
      /** @description Bad request syntax or unsupported method */
      400: {
        content: {
          "application/json": {
            detail: string;
            extra?:
              | {
                  [key: string]: unknown;
                }
              | null
              | unknown[];
            status_code: number;
          };
        };
        headers: {
          [name: string]: unknown;
        };
      };
    };
  };
  PlaylistsIdUpdate: {
    parameters: {
      cookie?: never;
      header?: never;
      path: {
        /** @description Identifier of the playlist to update. */
        id: string;
      };
      query?: {
        /** @description Relations to include in the response. */
        include?: null | string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PlaylistUpdateInput"];
      };
    };
    responses: {
      /** @description Request fulfilled, document follows */
      200: {
        content: {
          "application/json": components["schemas"]["playlists_models_Playlist"];
        };
        headers: {
          [name: string]: unknown;
        };
      };
      /** @description Bad request syntax or unsupported method */
      400: {
        content: {
          "application/json": {
            detail: string;
            extra?:
              | {
                  [key: string]: unknown;
                }
              | null
              | unknown[];
            status_code: number;
          };
        };
        headers: {
          [name: string]: unknown;
        };
      };
    };
  };
  PlaylistsList: {
    parameters: {
      cookie?: never;
      header?: never;
      path?: never;
      query?: {
        /** @description Relations to include in the response. */
        include?: null | string;
        /** @description Maximum number of playlists to return. */
        limit?: null | number;
        /** @description Number of playlists to skip. */
        offset?: null | number;
        /** @description Order to apply to the results. */
        order?: null | string;
        /** @description Filter to apply to find playlists. */
        where?: null | string;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Request fulfilled, document follows */
      200: {
        content: {
          "application/json": components["schemas"]["PlaylistList"];
        };
        headers: {
          [name: string]: unknown;
        };
      };
      /** @description Bad request syntax or unsupported method */
      400: {
        content: {
          "application/json": {
            detail: string;
            extra?:
              | {
                  [key: string]: unknown;
                }
              | null
              | unknown[];
            status_code: number;
          };
        };
        headers: {
          [name: string]: unknown;
        };
      };
    };
  };
  SseSubscribe: {
    parameters: {
      cookie?: never;
      header?: never;
      path?: never;
      query?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Request fulfilled, document follows */
      200: {
        content: {
          "": string;
        };
        headers: {
          [name: string]: unknown;
          /** @description File size in bytes */
          "content-length"?: string;
          /** @description Entity tag */
          etag?: string;
          /** @description Last modified data-time in RFC 2822 format */
          "last-modified"?: string;
        };
      };
    };
  };
};
